// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// ServerClientPortWithPrometheus implements provisioning.ServerClientPort interface with all methods wrapped
// with Prometheus metrics.
type ServerClientPortWithPrometheus struct {
	base         provisioning.ServerClientPort
	instanceName string
}

var serverClientPortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "server_client_port_duration_seconds",
		Help:       "serverClientPort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewServerClientPortWithPrometheus returns an instance of the provisioning.ServerClientPort decorated with prometheus summary metric.
func NewServerClientPortWithPrometheus(base provisioning.ServerClientPort, instanceName string) ServerClientPortWithPrometheus {
	return ServerClientPortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// AddApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) AddApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "AddApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddApplication(ctx, server, application)
}

// Evacuate implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) Evacuate(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Evacuate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Evacuate(ctx, server, callback)
}

// GetNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetNetworkConfig(ctx context.Context, server provisioning.Server) (serverSystemNetwork provisioning.ServerSystemNetwork, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetNetworkConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetNetworkConfig(ctx, server)
}

// GetOSData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetOSData(ctx context.Context, endpoint provisioning.Endpoint) (oSData api.OSData, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetOSData", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetOSData(ctx, endpoint)
}

// GetProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetProviderConfig(ctx context.Context, server provisioning.Server) (serverSystemProvider provisioning.ServerSystemProvider, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetProviderConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetProviderConfig(ctx, server)
}

// GetResources implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetResources(ctx context.Context, endpoint provisioning.Endpoint) (hardwareData api.HardwareData, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetResources", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetResources(ctx, endpoint)
}

// GetServerType implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetServerType(ctx context.Context, endpoint provisioning.Endpoint) (serverType api.ServerType, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetServerType", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetServerType(ctx, endpoint)
}

// GetStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetStorageConfig(ctx context.Context, server provisioning.Server) (serverSystemStorage provisioning.ServerSystemStorage, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetStorageConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetStorageConfig(ctx, server)
}

// GetSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetSystemKernel(ctx context.Context, server provisioning.Server) (serverSystemKernel provisioning.ServerSystemKernel, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemKernel", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemKernel(ctx, server)
}

// GetSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetSystemLogging(ctx context.Context, server provisioning.Server) (serverSystemLogging provisioning.ServerSystemLogging, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSystemLogging", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSystemLogging(ctx, server)
}

// GetUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetUpdateConfig(ctx context.Context, server provisioning.Server) (serverSystemUpdate provisioning.ServerSystemUpdate, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetUpdateConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetUpdateConfig(ctx, server)
}

// GetVersionData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) GetVersionData(ctx context.Context, server provisioning.Server) (serverVersionData api.ServerVersionData, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetVersionData", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetVersionData(ctx, server)
}

// IsReady implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) IsReady(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "IsReady", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.IsReady(ctx, server)
}

// Ping implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) Ping(ctx context.Context, endpoint provisioning.Endpoint) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Ping", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Ping(ctx, endpoint)
}

// Poweroff implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) Poweroff(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Poweroff", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Poweroff(ctx, server)
}

// Reboot implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) Reboot(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Reboot", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Reboot(ctx, server)
}

// RestartApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) RestartApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "RestartApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RestartApplication(ctx, server, application)
}

// Restore implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) Restore(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "Restore", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Restore(ctx, server, restoreModeSkip, callback)
}

// SystemFactoryReset implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) SystemFactoryReset(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "SystemFactoryReset", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SystemFactoryReset(ctx, endpoint, allowTPMResetFailure, seeds, providerConfig)
}

// UpdateApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateApplication(ctx, server, application)
}

// UpdateNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateNetworkConfig(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateNetworkConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateNetworkConfig(ctx, server)
}

// UpdateOS implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateOS(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateOS", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateOS(ctx, server)
}

// UpdateProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateProviderConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateProviderConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateProviderConfig(ctx, server, providerConfig)
}

// UpdateStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateStorageConfig(ctx context.Context, server provisioning.Server) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateStorageConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateStorageConfig(ctx, server)
}

// UpdateSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateSystemKernel(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemKernel", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemKernel(ctx, server, config)
}

// UpdateSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateSystemLogging(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemLogging", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemLogging(ctx, server, config)
}

// UpdateUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithPrometheus) UpdateUpdateConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		serverClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateUpdateConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateUpdateConfig(ctx, server, providerConfig)
}
