// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/shared/api"
)

// ServerClientPortWithSlog implements provisioning.ServerClientPort that is instrumented with slog logger.
type ServerClientPortWithSlog struct {
	_base                 provisioning.ServerClientPort
	_isInformativeErrFunc func(error) bool
}

type ServerClientPortWithSlogOption func(s *ServerClientPortWithSlog)

func ServerClientPortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) ServerClientPortWithSlogOption {
	return func(_base *ServerClientPortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewServerClientPortWithSlog instruments an implementation of the provisioning.ServerClientPort with simple logging.
func NewServerClientPortWithSlog(base provisioning.ServerClientPort, opts ...ServerClientPortWithSlogOption) ServerClientPortWithSlog {
	this := ServerClientPortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// AddApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) AddApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("application", application),
		)
	}
	log.DebugContext(ctx, "=> calling AddApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddApplication finished")
		}
	}()
	return _d._base.AddApplication(ctx, server, application)
}

// Evacuate implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) Evacuate(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("callback", callback),
		)
	}
	log.DebugContext(ctx, "=> calling Evacuate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Evacuate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Evacuate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Evacuate finished")
		}
	}()
	return _d._base.Evacuate(ctx, server, callback)
}

// GetNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetNetworkConfig(ctx context.Context, server provisioning.Server) (serverSystemNetwork provisioning.ServerSystemNetwork, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetNetworkConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemNetwork", serverSystemNetwork),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetNetworkConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetNetworkConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetNetworkConfig finished")
		}
	}()
	return _d._base.GetNetworkConfig(ctx, server)
}

// GetOSData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetOSData(ctx context.Context, endpoint provisioning.Endpoint) (oSData api.OSData, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
		)
	}
	log.DebugContext(ctx, "=> calling GetOSData")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("oSData", oSData),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetOSData returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetOSData returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetOSData finished")
		}
	}()
	return _d._base.GetOSData(ctx, endpoint)
}

// GetProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetProviderConfig(ctx context.Context, server provisioning.Server) (serverSystemProvider provisioning.ServerSystemProvider, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetProviderConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemProvider", serverSystemProvider),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetProviderConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetProviderConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetProviderConfig finished")
		}
	}()
	return _d._base.GetProviderConfig(ctx, server)
}

// GetResources implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetResources(ctx context.Context, endpoint provisioning.Endpoint) (hardwareData api.HardwareData, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
		)
	}
	log.DebugContext(ctx, "=> calling GetResources")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("hardwareData", hardwareData),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetResources returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetResources returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetResources finished")
		}
	}()
	return _d._base.GetResources(ctx, endpoint)
}

// GetServerType implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetServerType(ctx context.Context, endpoint provisioning.Endpoint) (serverType api.ServerType, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
		)
	}
	log.DebugContext(ctx, "=> calling GetServerType")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverType", serverType),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetServerType returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetServerType returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetServerType finished")
		}
	}()
	return _d._base.GetServerType(ctx, endpoint)
}

// GetStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetStorageConfig(ctx context.Context, server provisioning.Server) (serverSystemStorage provisioning.ServerSystemStorage, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetStorageConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemStorage", serverSystemStorage),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetStorageConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetStorageConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetStorageConfig finished")
		}
	}()
	return _d._base.GetStorageConfig(ctx, server)
}

// GetSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetSystemKernel(ctx context.Context, server provisioning.Server) (serverSystemKernel provisioning.ServerSystemKernel, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemKernel")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemKernel", serverSystemKernel),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemKernel returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemKernel returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemKernel finished")
		}
	}()
	return _d._base.GetSystemKernel(ctx, server)
}

// GetSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetSystemLogging(ctx context.Context, server provisioning.Server) (serverSystemLogging provisioning.ServerSystemLogging, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetSystemLogging")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemLogging", serverSystemLogging),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetSystemLogging returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetSystemLogging returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetSystemLogging finished")
		}
	}()
	return _d._base.GetSystemLogging(ctx, server)
}

// GetUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetUpdateConfig(ctx context.Context, server provisioning.Server) (serverSystemUpdate provisioning.ServerSystemUpdate, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetUpdateConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverSystemUpdate", serverSystemUpdate),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetUpdateConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetUpdateConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetUpdateConfig finished")
		}
	}()
	return _d._base.GetUpdateConfig(ctx, server)
}

// GetVersionData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) GetVersionData(ctx context.Context, server provisioning.Server) (serverVersionData api.ServerVersionData, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling GetVersionData")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("serverVersionData", serverVersionData),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetVersionData returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetVersionData returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetVersionData finished")
		}
	}()
	return _d._base.GetVersionData(ctx, server)
}

// IsReady implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) IsReady(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling IsReady")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method IsReady returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method IsReady returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method IsReady finished")
		}
	}()
	return _d._base.IsReady(ctx, server)
}

// Ping implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) Ping(ctx context.Context, endpoint provisioning.Endpoint) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
		)
	}
	log.DebugContext(ctx, "=> calling Ping")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Ping returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Ping returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Ping finished")
		}
	}()
	return _d._base.Ping(ctx, endpoint)
}

// Poweroff implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) Poweroff(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling Poweroff")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Poweroff returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Poweroff returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Poweroff finished")
		}
	}()
	return _d._base.Poweroff(ctx, server)
}

// Reboot implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) Reboot(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling Reboot")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Reboot returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Reboot returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Reboot finished")
		}
	}()
	return _d._base.Reboot(ctx, server)
}

// RestartApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) RestartApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("application", application),
		)
	}
	log.DebugContext(ctx, "=> calling RestartApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RestartApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RestartApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RestartApplication finished")
		}
	}()
	return _d._base.RestartApplication(ctx, server, application)
}

// Restore implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) Restore(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Bool("restoreModeSkip", restoreModeSkip),
			slog.Any("callback", callback),
		)
	}
	log.DebugContext(ctx, "=> calling Restore")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Restore returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Restore returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Restore finished")
		}
	}()
	return _d._base.Restore(ctx, server, restoreModeSkip, callback)
}

// SystemFactoryReset implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) SystemFactoryReset(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
			slog.Bool("allowTPMResetFailure", allowTPMResetFailure),
			slog.Any("seeds", seeds),
			slog.Any("providerConfig", providerConfig),
		)
	}
	log.DebugContext(ctx, "=> calling SystemFactoryReset")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method SystemFactoryReset returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method SystemFactoryReset returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method SystemFactoryReset finished")
		}
	}()
	return _d._base.SystemFactoryReset(ctx, endpoint, allowTPMResetFailure, seeds, providerConfig)
}

// UpdateApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.String("application", application),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateApplication finished")
		}
	}()
	return _d._base.UpdateApplication(ctx, server, application)
}

// UpdateNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateNetworkConfig(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateNetworkConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateNetworkConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateNetworkConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateNetworkConfig finished")
		}
	}()
	return _d._base.UpdateNetworkConfig(ctx, server)
}

// UpdateOS implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateOS(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateOS")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateOS returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateOS returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateOS finished")
		}
	}()
	return _d._base.UpdateOS(ctx, server)
}

// UpdateProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateProviderConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("providerConfig", providerConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateProviderConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateProviderConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateProviderConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateProviderConfig finished")
		}
	}()
	return _d._base.UpdateProviderConfig(ctx, server, providerConfig)
}

// UpdateStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateStorageConfig(ctx context.Context, server provisioning.Server) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateStorageConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateStorageConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateStorageConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateStorageConfig finished")
		}
	}()
	return _d._base.UpdateStorageConfig(ctx, server)
}

// UpdateSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateSystemKernel(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("config", config),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemKernel")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemKernel returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemKernel returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemKernel finished")
		}
	}()
	return _d._base.UpdateSystemKernel(ctx, server, config)
}

// UpdateSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateSystemLogging(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("config", config),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemLogging")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemLogging returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemLogging returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemLogging finished")
		}
	}()
	return _d._base.UpdateSystemLogging(ctx, server, config)
}

// UpdateUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithSlog) UpdateUpdateConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
			slog.Any("providerConfig", providerConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateUpdateConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateUpdateConfig returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateUpdateConfig returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateUpdateConfig finished")
		}
	}()
	return _d._base.UpdateUpdateConfig(ctx, server, providerConfig)
}
