// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// ServerClientPortWithErrorWrapper implements provisioning.ServerClientPort that wraps errors based custom logic.
type ServerClientPortWithErrorWrapper struct {
	_base        provisioning.ServerClientPort
	_wrapErrFunc func(error) error
}

// NewServerClientPortWithErrorWrapper instruments an implementation of the provisioning.ServerClientPort with error wrapping.
func NewServerClientPortWithErrorWrapper(base provisioning.ServerClientPort, wrapErrFunc func(error) error) ServerClientPortWithErrorWrapper {
	this := ServerClientPortWithErrorWrapper{
		_base:        base,
		_wrapErrFunc: wrapErrFunc,
	}

	return this
}

// AddApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) AddApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.AddApplication(ctx, server, application)
}

// Evacuate implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) Evacuate(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Evacuate(ctx, server, callback)
}

// GetNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetNetworkConfig(ctx context.Context, server provisioning.Server) (serverSystemNetwork provisioning.ServerSystemNetwork, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetNetworkConfig(ctx, server)
}

// GetOSData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetOSData(ctx context.Context, endpoint provisioning.Endpoint) (oSData api.OSData, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetOSData(ctx, endpoint)
}

// GetProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetProviderConfig(ctx context.Context, server provisioning.Server) (serverSystemProvider provisioning.ServerSystemProvider, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetProviderConfig(ctx, server)
}

// GetResources implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetResources(ctx context.Context, endpoint provisioning.Endpoint) (hardwareData api.HardwareData, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetResources(ctx, endpoint)
}

// GetServerType implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetServerType(ctx context.Context, endpoint provisioning.Endpoint) (serverType api.ServerType, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetServerType(ctx, endpoint)
}

// GetStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetStorageConfig(ctx context.Context, server provisioning.Server) (serverSystemStorage provisioning.ServerSystemStorage, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetStorageConfig(ctx, server)
}

// GetSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetSystemKernel(ctx context.Context, server provisioning.Server) (serverSystemKernel provisioning.ServerSystemKernel, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetSystemKernel(ctx, server)
}

// GetSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetSystemLogging(ctx context.Context, server provisioning.Server) (serverSystemLogging provisioning.ServerSystemLogging, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetSystemLogging(ctx, server)
}

// GetUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetUpdateConfig(ctx context.Context, server provisioning.Server) (serverSystemUpdate provisioning.ServerSystemUpdate, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetUpdateConfig(ctx, server)
}

// GetVersionData implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) GetVersionData(ctx context.Context, server provisioning.Server) (serverVersionData api.ServerVersionData, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetVersionData(ctx, server)
}

// IsReady implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) IsReady(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.IsReady(ctx, server)
}

// Ping implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) Ping(ctx context.Context, endpoint provisioning.Endpoint) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Ping(ctx, endpoint)
}

// Poweroff implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) Poweroff(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Poweroff(ctx, server)
}

// Reboot implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) Reboot(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Reboot(ctx, server)
}

// RestartApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) RestartApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.RestartApplication(ctx, server, application)
}

// Restore implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) Restore(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.Restore(ctx, server, restoreModeSkip, callback)
}

// SystemFactoryReset implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) SystemFactoryReset(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.SystemFactoryReset(ctx, endpoint, allowTPMResetFailure, seeds, providerConfig)
}

// UpdateApplication implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateApplication(ctx context.Context, server provisioning.Server, application string) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateApplication(ctx, server, application)
}

// UpdateNetworkConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateNetworkConfig(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateNetworkConfig(ctx, server)
}

// UpdateOS implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateOS(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateOS(ctx, server)
}

// UpdateProviderConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateProviderConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateProviderConfig(ctx, server, providerConfig)
}

// UpdateStorageConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateStorageConfig(ctx context.Context, server provisioning.Server) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateStorageConfig(ctx, server)
}

// UpdateSystemKernel implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateSystemKernel(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateSystemKernel(ctx, server, config)
}

// UpdateSystemLogging implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateSystemLogging(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateSystemLogging(ctx, server, config)
}

// UpdateUpdateConfig implements provisioning.ServerClientPort.
func (_d ServerClientPortWithErrorWrapper) UpdateUpdateConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) (err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.UpdateUpdateConfig(ctx, server, providerConfig)
}
