// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/system"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// componentDatabaseRepo identifies the log records of this decorator and allows the
// log level to be configured for it individually.
var componentDatabaseRepo = logger.RegisterComponent("system.database_repo")

// DatabaseRepoWithSlog implements system.DatabaseRepo that is instrumented with slog logger.
type DatabaseRepoWithSlog struct {
	_base      system.DatabaseRepo
	_component logger.Component
}

type DatabaseRepoWithSlogOption func(s *DatabaseRepoWithSlog)

// DatabaseRepoWithSlogWithComponent overrides the component this instance is
// attributed to. Use it to tell several instances of the same interface apart,
// e.g. the individual members of a chain.
func DatabaseRepoWithSlogWithComponent(component logger.Component) DatabaseRepoWithSlogOption {
	return func(_base *DatabaseRepoWithSlog) {
		_base._component = component
	}
}

// NewDatabaseRepoWithSlog instruments an implementation of the system.DatabaseRepo with simple logging.
func NewDatabaseRepoWithSlog(base system.DatabaseRepo, opts ...DatabaseRepoWithSlogOption) DatabaseRepoWithSlog {
	this := DatabaseRepoWithSlog{
		_base:      base,
		_component: componentDatabaseRepo,
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// SchemaVersion implements system.DatabaseRepo.
func (_d DatabaseRepoWithSlog) SchemaVersion(ctx context.Context, dir string) (current int, latest int, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("dir", dir),
		)
	}
	log.DebugContext(ctx, "=> calling SchemaVersion")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Int("current", current),
				slog.Int("latest", latest),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method SchemaVersion returned an error")
		} else {
			log.DebugContext(ctx, "<= method SchemaVersion finished")
		}
	}()
	return _d._base.SchemaVersion(ctx, dir)
}

// Snapshot implements system.DatabaseRepo.
func (_d DatabaseRepoWithSlog) Snapshot(ctx context.Context, dir string) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("dir", dir),
		)
	}
	log.DebugContext(ctx, "=> calling Snapshot")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Snapshot returned an error")
		} else {
			log.DebugContext(ctx, "<= method Snapshot finished")
		}
	}()
	return _d._base.Snapshot(ctx, dir)
}
