// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/system"
)

// DatabaseRepoWithPrometheus implements system.DatabaseRepo interface with all methods wrapped
// with Prometheus metrics.
type DatabaseRepoWithPrometheus struct {
	base         system.DatabaseRepo
	instanceName string
}

var databaseRepoDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "database_repo_duration_seconds",
		Help:       "databaseRepo runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewDatabaseRepoWithPrometheus returns an instance of the system.DatabaseRepo decorated with prometheus summary metric.
func NewDatabaseRepoWithPrometheus(base system.DatabaseRepo, instanceName string) DatabaseRepoWithPrometheus {
	return DatabaseRepoWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// SchemaVersion implements system.DatabaseRepo.
func (_d DatabaseRepoWithPrometheus) SchemaVersion(ctx context.Context, dir string) (current int, latest int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		databaseRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "SchemaVersion", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SchemaVersion(ctx, dir)
}

// Snapshot implements system.DatabaseRepo.
func (_d DatabaseRepoWithPrometheus) Snapshot(ctx context.Context, dir string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		databaseRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "Snapshot", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Snapshot(ctx, dir)
}
