// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/shared/api"
)

// Ensure that ServerClientPortMock does implement provisioning.ServerClientPort.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.ServerClientPort = &ServerClientPortMock{}

// ServerClientPortMock is a mock implementation of provisioning.ServerClientPort.
//
//	func TestSomethingThatUsesServerClientPort(t *testing.T) {
//
//		// make and configure a mocked provisioning.ServerClientPort
//		mockedServerClientPort := &ServerClientPortMock{
//			AddApplicationFunc: func(ctx context.Context, server provisioning.Server, application string) error {
//				panic("mock out the AddApplication method")
//			},
//			EvacuateFunc: func(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) error {
//				panic("mock out the Evacuate method")
//			},
//			GetNetworkConfigFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemNetwork, error) {
//				panic("mock out the GetNetworkConfig method")
//			},
//			GetOSDataFunc: func(ctx context.Context, endpoint provisioning.Endpoint) (api.OSData, error) {
//				panic("mock out the GetOSData method")
//			},
//			GetProviderConfigFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemProvider, error) {
//				panic("mock out the GetProviderConfig method")
//			},
//			GetResourcesFunc: func(ctx context.Context, endpoint provisioning.Endpoint) (api.HardwareData, error) {
//				panic("mock out the GetResources method")
//			},
//			GetServerTypeFunc: func(ctx context.Context, endpoint provisioning.Endpoint) (api.ServerType, error) {
//				panic("mock out the GetServerType method")
//			},
//			GetStorageConfigFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemStorage, error) {
//				panic("mock out the GetStorageConfig method")
//			},
//			GetSystemKernelFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemKernel, error) {
//				panic("mock out the GetSystemKernel method")
//			},
//			GetSystemLoggingFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemLogging, error) {
//				panic("mock out the GetSystemLogging method")
//			},
//			GetUpdateConfigFunc: func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemUpdate, error) {
//				panic("mock out the GetUpdateConfig method")
//			},
//			GetVersionDataFunc: func(ctx context.Context, server provisioning.Server) (api.ServerVersionData, error) {
//				panic("mock out the GetVersionData method")
//			},
//			IsReadyFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the IsReady method")
//			},
//			PingFunc: func(ctx context.Context, endpoint provisioning.Endpoint) error {
//				panic("mock out the Ping method")
//			},
//			PoweroffFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the Poweroff method")
//			},
//			RebootFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the Reboot method")
//			},
//			RestartApplicationFunc: func(ctx context.Context, server provisioning.Server, application string) error {
//				panic("mock out the RestartApplication method")
//			},
//			RestoreFunc: func(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) error {
//				panic("mock out the Restore method")
//			},
//			SystemFactoryResetFunc: func(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) error {
//				panic("mock out the SystemFactoryReset method")
//			},
//			UpdateApplicationFunc: func(ctx context.Context, server provisioning.Server, application string) error {
//				panic("mock out the UpdateApplication method")
//			},
//			UpdateNetworkConfigFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the UpdateNetworkConfig method")
//			},
//			UpdateOSFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the UpdateOS method")
//			},
//			UpdateProviderConfigFunc: func(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) error {
//				panic("mock out the UpdateProviderConfig method")
//			},
//			UpdateStorageConfigFunc: func(ctx context.Context, server provisioning.Server) error {
//				panic("mock out the UpdateStorageConfig method")
//			},
//			UpdateSystemKernelFunc: func(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) error {
//				panic("mock out the UpdateSystemKernel method")
//			},
//			UpdateSystemLoggingFunc: func(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) error {
//				panic("mock out the UpdateSystemLogging method")
//			},
//			UpdateUpdateConfigFunc: func(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) error {
//				panic("mock out the UpdateUpdateConfig method")
//			},
//		}
//
//		// use mockedServerClientPort in code that requires provisioning.ServerClientPort
//		// and then make assertions.
//
//	}
type ServerClientPortMock struct {
	// AddApplicationFunc mocks the AddApplication method.
	AddApplicationFunc func(ctx context.Context, server provisioning.Server, application string) error

	// EvacuateFunc mocks the Evacuate method.
	EvacuateFunc func(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) error

	// GetNetworkConfigFunc mocks the GetNetworkConfig method.
	GetNetworkConfigFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemNetwork, error)

	// GetOSDataFunc mocks the GetOSData method.
	GetOSDataFunc func(ctx context.Context, endpoint provisioning.Endpoint) (api.OSData, error)

	// GetProviderConfigFunc mocks the GetProviderConfig method.
	GetProviderConfigFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemProvider, error)

	// GetResourcesFunc mocks the GetResources method.
	GetResourcesFunc func(ctx context.Context, endpoint provisioning.Endpoint) (api.HardwareData, error)

	// GetServerTypeFunc mocks the GetServerType method.
	GetServerTypeFunc func(ctx context.Context, endpoint provisioning.Endpoint) (api.ServerType, error)

	// GetStorageConfigFunc mocks the GetStorageConfig method.
	GetStorageConfigFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemStorage, error)

	// GetSystemKernelFunc mocks the GetSystemKernel method.
	GetSystemKernelFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemKernel, error)

	// GetSystemLoggingFunc mocks the GetSystemLogging method.
	GetSystemLoggingFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemLogging, error)

	// GetUpdateConfigFunc mocks the GetUpdateConfig method.
	GetUpdateConfigFunc func(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemUpdate, error)

	// GetVersionDataFunc mocks the GetVersionData method.
	GetVersionDataFunc func(ctx context.Context, server provisioning.Server) (api.ServerVersionData, error)

	// IsReadyFunc mocks the IsReady method.
	IsReadyFunc func(ctx context.Context, server provisioning.Server) error

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context, endpoint provisioning.Endpoint) error

	// PoweroffFunc mocks the Poweroff method.
	PoweroffFunc func(ctx context.Context, server provisioning.Server) error

	// RebootFunc mocks the Reboot method.
	RebootFunc func(ctx context.Context, server provisioning.Server) error

	// RestartApplicationFunc mocks the RestartApplication method.
	RestartApplicationFunc func(ctx context.Context, server provisioning.Server, application string) error

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) error

	// SystemFactoryResetFunc mocks the SystemFactoryReset method.
	SystemFactoryResetFunc func(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) error

	// UpdateApplicationFunc mocks the UpdateApplication method.
	UpdateApplicationFunc func(ctx context.Context, server provisioning.Server, application string) error

	// UpdateNetworkConfigFunc mocks the UpdateNetworkConfig method.
	UpdateNetworkConfigFunc func(ctx context.Context, server provisioning.Server) error

	// UpdateOSFunc mocks the UpdateOS method.
	UpdateOSFunc func(ctx context.Context, server provisioning.Server) error

	// UpdateProviderConfigFunc mocks the UpdateProviderConfig method.
	UpdateProviderConfigFunc func(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) error

	// UpdateStorageConfigFunc mocks the UpdateStorageConfig method.
	UpdateStorageConfigFunc func(ctx context.Context, server provisioning.Server) error

	// UpdateSystemKernelFunc mocks the UpdateSystemKernel method.
	UpdateSystemKernelFunc func(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) error

	// UpdateSystemLoggingFunc mocks the UpdateSystemLogging method.
	UpdateSystemLoggingFunc func(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) error

	// UpdateUpdateConfigFunc mocks the UpdateUpdateConfig method.
	UpdateUpdateConfigFunc func(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// AddApplication holds details about calls to the AddApplication method.
		AddApplication []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Application is the application argument value.
			Application string
		}
		// Evacuate holds details about calls to the Evacuate method.
		Evacuate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Callback is the callback argument value.
			Callback func(ctx context.Context, err error)
		}
		// GetNetworkConfig holds details about calls to the GetNetworkConfig method.
		GetNetworkConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetOSData holds details about calls to the GetOSData method.
		GetOSData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint provisioning.Endpoint
		}
		// GetProviderConfig holds details about calls to the GetProviderConfig method.
		GetProviderConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetResources holds details about calls to the GetResources method.
		GetResources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint provisioning.Endpoint
		}
		// GetServerType holds details about calls to the GetServerType method.
		GetServerType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint provisioning.Endpoint
		}
		// GetStorageConfig holds details about calls to the GetStorageConfig method.
		GetStorageConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetSystemKernel holds details about calls to the GetSystemKernel method.
		GetSystemKernel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetSystemLogging holds details about calls to the GetSystemLogging method.
		GetSystemLogging []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetUpdateConfig holds details about calls to the GetUpdateConfig method.
		GetUpdateConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// GetVersionData holds details about calls to the GetVersionData method.
		GetVersionData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// IsReady holds details about calls to the IsReady method.
		IsReady []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint provisioning.Endpoint
		}
		// Poweroff holds details about calls to the Poweroff method.
		Poweroff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// Reboot holds details about calls to the Reboot method.
		Reboot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// RestartApplication holds details about calls to the RestartApplication method.
		RestartApplication []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Application is the application argument value.
			Application string
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// RestoreModeSkip is the restoreModeSkip argument value.
			RestoreModeSkip bool
			// Callback is the callback argument value.
			Callback func(ctx context.Context, err error)
		}
		// SystemFactoryReset holds details about calls to the SystemFactoryReset method.
		SystemFactoryReset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint provisioning.Endpoint
			// AllowTPMResetFailure is the allowTPMResetFailure argument value.
			AllowTPMResetFailure bool
			// Seeds is the seeds argument value.
			Seeds provisioning.TokenImageSeedConfigs
			// ProviderConfig is the providerConfig argument value.
			ProviderConfig api.TokenProviderConfig
		}
		// UpdateApplication holds details about calls to the UpdateApplication method.
		UpdateApplication []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Application is the application argument value.
			Application string
		}
		// UpdateNetworkConfig holds details about calls to the UpdateNetworkConfig method.
		UpdateNetworkConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// UpdateOS holds details about calls to the UpdateOS method.
		UpdateOS []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// UpdateProviderConfig holds details about calls to the UpdateProviderConfig method.
		UpdateProviderConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// ProviderConfig is the providerConfig argument value.
			ProviderConfig provisioning.ServerSystemProvider
		}
		// UpdateStorageConfig holds details about calls to the UpdateStorageConfig method.
		UpdateStorageConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
		}
		// UpdateSystemKernel holds details about calls to the UpdateSystemKernel method.
		UpdateSystemKernel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Config is the config argument value.
			Config provisioning.ServerSystemKernel
		}
		// UpdateSystemLogging holds details about calls to the UpdateSystemLogging method.
		UpdateSystemLogging []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// Config is the config argument value.
			Config provisioning.ServerSystemLogging
		}
		// UpdateUpdateConfig holds details about calls to the UpdateUpdateConfig method.
		UpdateUpdateConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Server is the server argument value.
			Server provisioning.Server
			// ProviderConfig is the providerConfig argument value.
			ProviderConfig provisioning.ServerSystemUpdate
		}
	}
	lockAddApplication       sync.RWMutex
	lockEvacuate             sync.RWMutex
	lockGetNetworkConfig     sync.RWMutex
	lockGetOSData            sync.RWMutex
	lockGetProviderConfig    sync.RWMutex
	lockGetResources         sync.RWMutex
	lockGetServerType        sync.RWMutex
	lockGetStorageConfig     sync.RWMutex
	lockGetSystemKernel      sync.RWMutex
	lockGetSystemLogging     sync.RWMutex
	lockGetUpdateConfig      sync.RWMutex
	lockGetVersionData       sync.RWMutex
	lockIsReady              sync.RWMutex
	lockPing                 sync.RWMutex
	lockPoweroff             sync.RWMutex
	lockReboot               sync.RWMutex
	lockRestartApplication   sync.RWMutex
	lockRestore              sync.RWMutex
	lockSystemFactoryReset   sync.RWMutex
	lockUpdateApplication    sync.RWMutex
	lockUpdateNetworkConfig  sync.RWMutex
	lockUpdateOS             sync.RWMutex
	lockUpdateProviderConfig sync.RWMutex
	lockUpdateStorageConfig  sync.RWMutex
	lockUpdateSystemKernel   sync.RWMutex
	lockUpdateSystemLogging  sync.RWMutex
	lockUpdateUpdateConfig   sync.RWMutex
}

// AddApplication calls AddApplicationFunc.
func (mock *ServerClientPortMock) AddApplication(ctx context.Context, server provisioning.Server, application string) error {
	if mock.AddApplicationFunc == nil {
		panic("ServerClientPortMock.AddApplicationFunc: method is nil but ServerClientPort.AddApplication was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}{
		Ctx:         ctx,
		Server:      server,
		Application: application,
	}
	mock.lockAddApplication.Lock()
	mock.calls.AddApplication = append(mock.calls.AddApplication, callInfo)
	mock.lockAddApplication.Unlock()
	return mock.AddApplicationFunc(ctx, server, application)
}

// AddApplicationCalls gets all the calls that were made to AddApplication.
// Check the length with:
//
//	len(mockedServerClientPort.AddApplicationCalls())
func (mock *ServerClientPortMock) AddApplicationCalls() []struct {
	Ctx         context.Context
	Server      provisioning.Server
	Application string
} {
	var calls []struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}
	mock.lockAddApplication.RLock()
	calls = mock.calls.AddApplication
	mock.lockAddApplication.RUnlock()
	return calls
}

// Evacuate calls EvacuateFunc.
func (mock *ServerClientPortMock) Evacuate(ctx context.Context, server provisioning.Server, callback func(ctx context.Context, err error)) error {
	if mock.EvacuateFunc == nil {
		panic("ServerClientPortMock.EvacuateFunc: method is nil but ServerClientPort.Evacuate was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Server   provisioning.Server
		Callback func(ctx context.Context, err error)
	}{
		Ctx:      ctx,
		Server:   server,
		Callback: callback,
	}
	mock.lockEvacuate.Lock()
	mock.calls.Evacuate = append(mock.calls.Evacuate, callInfo)
	mock.lockEvacuate.Unlock()
	return mock.EvacuateFunc(ctx, server, callback)
}

// EvacuateCalls gets all the calls that were made to Evacuate.
// Check the length with:
//
//	len(mockedServerClientPort.EvacuateCalls())
func (mock *ServerClientPortMock) EvacuateCalls() []struct {
	Ctx      context.Context
	Server   provisioning.Server
	Callback func(ctx context.Context, err error)
} {
	var calls []struct {
		Ctx      context.Context
		Server   provisioning.Server
		Callback func(ctx context.Context, err error)
	}
	mock.lockEvacuate.RLock()
	calls = mock.calls.Evacuate
	mock.lockEvacuate.RUnlock()
	return calls
}

// GetNetworkConfig calls GetNetworkConfigFunc.
func (mock *ServerClientPortMock) GetNetworkConfig(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemNetwork, error) {
	if mock.GetNetworkConfigFunc == nil {
		panic("ServerClientPortMock.GetNetworkConfigFunc: method is nil but ServerClientPort.GetNetworkConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetNetworkConfig.Lock()
	mock.calls.GetNetworkConfig = append(mock.calls.GetNetworkConfig, callInfo)
	mock.lockGetNetworkConfig.Unlock()
	return mock.GetNetworkConfigFunc(ctx, server)
}

// GetNetworkConfigCalls gets all the calls that were made to GetNetworkConfig.
// Check the length with:
//
//	len(mockedServerClientPort.GetNetworkConfigCalls())
func (mock *ServerClientPortMock) GetNetworkConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetNetworkConfig.RLock()
	calls = mock.calls.GetNetworkConfig
	mock.lockGetNetworkConfig.RUnlock()
	return calls
}

// GetOSData calls GetOSDataFunc.
func (mock *ServerClientPortMock) GetOSData(ctx context.Context, endpoint provisioning.Endpoint) (api.OSData, error) {
	if mock.GetOSDataFunc == nil {
		panic("ServerClientPortMock.GetOSDataFunc: method is nil but ServerClientPort.GetOSData was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}{
		Ctx:      ctx,
		Endpoint: endpoint,
	}
	mock.lockGetOSData.Lock()
	mock.calls.GetOSData = append(mock.calls.GetOSData, callInfo)
	mock.lockGetOSData.Unlock()
	return mock.GetOSDataFunc(ctx, endpoint)
}

// GetOSDataCalls gets all the calls that were made to GetOSData.
// Check the length with:
//
//	len(mockedServerClientPort.GetOSDataCalls())
func (mock *ServerClientPortMock) GetOSDataCalls() []struct {
	Ctx      context.Context
	Endpoint provisioning.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}
	mock.lockGetOSData.RLock()
	calls = mock.calls.GetOSData
	mock.lockGetOSData.RUnlock()
	return calls
}

// GetProviderConfig calls GetProviderConfigFunc.
func (mock *ServerClientPortMock) GetProviderConfig(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemProvider, error) {
	if mock.GetProviderConfigFunc == nil {
		panic("ServerClientPortMock.GetProviderConfigFunc: method is nil but ServerClientPort.GetProviderConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetProviderConfig.Lock()
	mock.calls.GetProviderConfig = append(mock.calls.GetProviderConfig, callInfo)
	mock.lockGetProviderConfig.Unlock()
	return mock.GetProviderConfigFunc(ctx, server)
}

// GetProviderConfigCalls gets all the calls that were made to GetProviderConfig.
// Check the length with:
//
//	len(mockedServerClientPort.GetProviderConfigCalls())
func (mock *ServerClientPortMock) GetProviderConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetProviderConfig.RLock()
	calls = mock.calls.GetProviderConfig
	mock.lockGetProviderConfig.RUnlock()
	return calls
}

// GetResources calls GetResourcesFunc.
func (mock *ServerClientPortMock) GetResources(ctx context.Context, endpoint provisioning.Endpoint) (api.HardwareData, error) {
	if mock.GetResourcesFunc == nil {
		panic("ServerClientPortMock.GetResourcesFunc: method is nil but ServerClientPort.GetResources was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}{
		Ctx:      ctx,
		Endpoint: endpoint,
	}
	mock.lockGetResources.Lock()
	mock.calls.GetResources = append(mock.calls.GetResources, callInfo)
	mock.lockGetResources.Unlock()
	return mock.GetResourcesFunc(ctx, endpoint)
}

// GetResourcesCalls gets all the calls that were made to GetResources.
// Check the length with:
//
//	len(mockedServerClientPort.GetResourcesCalls())
func (mock *ServerClientPortMock) GetResourcesCalls() []struct {
	Ctx      context.Context
	Endpoint provisioning.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}
	mock.lockGetResources.RLock()
	calls = mock.calls.GetResources
	mock.lockGetResources.RUnlock()
	return calls
}

// GetServerType calls GetServerTypeFunc.
func (mock *ServerClientPortMock) GetServerType(ctx context.Context, endpoint provisioning.Endpoint) (api.ServerType, error) {
	if mock.GetServerTypeFunc == nil {
		panic("ServerClientPortMock.GetServerTypeFunc: method is nil but ServerClientPort.GetServerType was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}{
		Ctx:      ctx,
		Endpoint: endpoint,
	}
	mock.lockGetServerType.Lock()
	mock.calls.GetServerType = append(mock.calls.GetServerType, callInfo)
	mock.lockGetServerType.Unlock()
	return mock.GetServerTypeFunc(ctx, endpoint)
}

// GetServerTypeCalls gets all the calls that were made to GetServerType.
// Check the length with:
//
//	len(mockedServerClientPort.GetServerTypeCalls())
func (mock *ServerClientPortMock) GetServerTypeCalls() []struct {
	Ctx      context.Context
	Endpoint provisioning.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}
	mock.lockGetServerType.RLock()
	calls = mock.calls.GetServerType
	mock.lockGetServerType.RUnlock()
	return calls
}

// GetStorageConfig calls GetStorageConfigFunc.
func (mock *ServerClientPortMock) GetStorageConfig(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemStorage, error) {
	if mock.GetStorageConfigFunc == nil {
		panic("ServerClientPortMock.GetStorageConfigFunc: method is nil but ServerClientPort.GetStorageConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetStorageConfig.Lock()
	mock.calls.GetStorageConfig = append(mock.calls.GetStorageConfig, callInfo)
	mock.lockGetStorageConfig.Unlock()
	return mock.GetStorageConfigFunc(ctx, server)
}

// GetStorageConfigCalls gets all the calls that were made to GetStorageConfig.
// Check the length with:
//
//	len(mockedServerClientPort.GetStorageConfigCalls())
func (mock *ServerClientPortMock) GetStorageConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetStorageConfig.RLock()
	calls = mock.calls.GetStorageConfig
	mock.lockGetStorageConfig.RUnlock()
	return calls
}

// GetSystemKernel calls GetSystemKernelFunc.
func (mock *ServerClientPortMock) GetSystemKernel(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemKernel, error) {
	if mock.GetSystemKernelFunc == nil {
		panic("ServerClientPortMock.GetSystemKernelFunc: method is nil but ServerClientPort.GetSystemKernel was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetSystemKernel.Lock()
	mock.calls.GetSystemKernel = append(mock.calls.GetSystemKernel, callInfo)
	mock.lockGetSystemKernel.Unlock()
	return mock.GetSystemKernelFunc(ctx, server)
}

// GetSystemKernelCalls gets all the calls that were made to GetSystemKernel.
// Check the length with:
//
//	len(mockedServerClientPort.GetSystemKernelCalls())
func (mock *ServerClientPortMock) GetSystemKernelCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetSystemKernel.RLock()
	calls = mock.calls.GetSystemKernel
	mock.lockGetSystemKernel.RUnlock()
	return calls
}

// GetSystemLogging calls GetSystemLoggingFunc.
func (mock *ServerClientPortMock) GetSystemLogging(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemLogging, error) {
	if mock.GetSystemLoggingFunc == nil {
		panic("ServerClientPortMock.GetSystemLoggingFunc: method is nil but ServerClientPort.GetSystemLogging was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetSystemLogging.Lock()
	mock.calls.GetSystemLogging = append(mock.calls.GetSystemLogging, callInfo)
	mock.lockGetSystemLogging.Unlock()
	return mock.GetSystemLoggingFunc(ctx, server)
}

// GetSystemLoggingCalls gets all the calls that were made to GetSystemLogging.
// Check the length with:
//
//	len(mockedServerClientPort.GetSystemLoggingCalls())
func (mock *ServerClientPortMock) GetSystemLoggingCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetSystemLogging.RLock()
	calls = mock.calls.GetSystemLogging
	mock.lockGetSystemLogging.RUnlock()
	return calls
}

// GetUpdateConfig calls GetUpdateConfigFunc.
func (mock *ServerClientPortMock) GetUpdateConfig(ctx context.Context, server provisioning.Server) (provisioning.ServerSystemUpdate, error) {
	if mock.GetUpdateConfigFunc == nil {
		panic("ServerClientPortMock.GetUpdateConfigFunc: method is nil but ServerClientPort.GetUpdateConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetUpdateConfig.Lock()
	mock.calls.GetUpdateConfig = append(mock.calls.GetUpdateConfig, callInfo)
	mock.lockGetUpdateConfig.Unlock()
	return mock.GetUpdateConfigFunc(ctx, server)
}

// GetUpdateConfigCalls gets all the calls that were made to GetUpdateConfig.
// Check the length with:
//
//	len(mockedServerClientPort.GetUpdateConfigCalls())
func (mock *ServerClientPortMock) GetUpdateConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetUpdateConfig.RLock()
	calls = mock.calls.GetUpdateConfig
	mock.lockGetUpdateConfig.RUnlock()
	return calls
}

// GetVersionData calls GetVersionDataFunc.
func (mock *ServerClientPortMock) GetVersionData(ctx context.Context, server provisioning.Server) (api.ServerVersionData, error) {
	if mock.GetVersionDataFunc == nil {
		panic("ServerClientPortMock.GetVersionDataFunc: method is nil but ServerClientPort.GetVersionData was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockGetVersionData.Lock()
	mock.calls.GetVersionData = append(mock.calls.GetVersionData, callInfo)
	mock.lockGetVersionData.Unlock()
	return mock.GetVersionDataFunc(ctx, server)
}

// GetVersionDataCalls gets all the calls that were made to GetVersionData.
// Check the length with:
//
//	len(mockedServerClientPort.GetVersionDataCalls())
func (mock *ServerClientPortMock) GetVersionDataCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockGetVersionData.RLock()
	calls = mock.calls.GetVersionData
	mock.lockGetVersionData.RUnlock()
	return calls
}

// IsReady calls IsReadyFunc.
func (mock *ServerClientPortMock) IsReady(ctx context.Context, server provisioning.Server) error {
	if mock.IsReadyFunc == nil {
		panic("ServerClientPortMock.IsReadyFunc: method is nil but ServerClientPort.IsReady was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockIsReady.Lock()
	mock.calls.IsReady = append(mock.calls.IsReady, callInfo)
	mock.lockIsReady.Unlock()
	return mock.IsReadyFunc(ctx, server)
}

// IsReadyCalls gets all the calls that were made to IsReady.
// Check the length with:
//
//	len(mockedServerClientPort.IsReadyCalls())
func (mock *ServerClientPortMock) IsReadyCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockIsReady.RLock()
	calls = mock.calls.IsReady
	mock.lockIsReady.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *ServerClientPortMock) Ping(ctx context.Context, endpoint provisioning.Endpoint) error {
	if mock.PingFunc == nil {
		panic("ServerClientPortMock.PingFunc: method is nil but ServerClientPort.Ping was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}{
		Ctx:      ctx,
		Endpoint: endpoint,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx, endpoint)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedServerClientPort.PingCalls())
func (mock *ServerClientPortMock) PingCalls() []struct {
	Ctx      context.Context
	Endpoint provisioning.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Endpoint provisioning.Endpoint
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Poweroff calls PoweroffFunc.
func (mock *ServerClientPortMock) Poweroff(ctx context.Context, server provisioning.Server) error {
	if mock.PoweroffFunc == nil {
		panic("ServerClientPortMock.PoweroffFunc: method is nil but ServerClientPort.Poweroff was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockPoweroff.Lock()
	mock.calls.Poweroff = append(mock.calls.Poweroff, callInfo)
	mock.lockPoweroff.Unlock()
	return mock.PoweroffFunc(ctx, server)
}

// PoweroffCalls gets all the calls that were made to Poweroff.
// Check the length with:
//
//	len(mockedServerClientPort.PoweroffCalls())
func (mock *ServerClientPortMock) PoweroffCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockPoweroff.RLock()
	calls = mock.calls.Poweroff
	mock.lockPoweroff.RUnlock()
	return calls
}

// Reboot calls RebootFunc.
func (mock *ServerClientPortMock) Reboot(ctx context.Context, server provisioning.Server) error {
	if mock.RebootFunc == nil {
		panic("ServerClientPortMock.RebootFunc: method is nil but ServerClientPort.Reboot was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockReboot.Lock()
	mock.calls.Reboot = append(mock.calls.Reboot, callInfo)
	mock.lockReboot.Unlock()
	return mock.RebootFunc(ctx, server)
}

// RebootCalls gets all the calls that were made to Reboot.
// Check the length with:
//
//	len(mockedServerClientPort.RebootCalls())
func (mock *ServerClientPortMock) RebootCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockReboot.RLock()
	calls = mock.calls.Reboot
	mock.lockReboot.RUnlock()
	return calls
}

// RestartApplication calls RestartApplicationFunc.
func (mock *ServerClientPortMock) RestartApplication(ctx context.Context, server provisioning.Server, application string) error {
	if mock.RestartApplicationFunc == nil {
		panic("ServerClientPortMock.RestartApplicationFunc: method is nil but ServerClientPort.RestartApplication was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}{
		Ctx:         ctx,
		Server:      server,
		Application: application,
	}
	mock.lockRestartApplication.Lock()
	mock.calls.RestartApplication = append(mock.calls.RestartApplication, callInfo)
	mock.lockRestartApplication.Unlock()
	return mock.RestartApplicationFunc(ctx, server, application)
}

// RestartApplicationCalls gets all the calls that were made to RestartApplication.
// Check the length with:
//
//	len(mockedServerClientPort.RestartApplicationCalls())
func (mock *ServerClientPortMock) RestartApplicationCalls() []struct {
	Ctx         context.Context
	Server      provisioning.Server
	Application string
} {
	var calls []struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}
	mock.lockRestartApplication.RLock()
	calls = mock.calls.RestartApplication
	mock.lockRestartApplication.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *ServerClientPortMock) Restore(ctx context.Context, server provisioning.Server, restoreModeSkip bool, callback func(ctx context.Context, err error)) error {
	if mock.RestoreFunc == nil {
		panic("ServerClientPortMock.RestoreFunc: method is nil but ServerClientPort.Restore was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		Server          provisioning.Server
		RestoreModeSkip bool
		Callback        func(ctx context.Context, err error)
	}{
		Ctx:             ctx,
		Server:          server,
		RestoreModeSkip: restoreModeSkip,
		Callback:        callback,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, server, restoreModeSkip, callback)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedServerClientPort.RestoreCalls())
func (mock *ServerClientPortMock) RestoreCalls() []struct {
	Ctx             context.Context
	Server          provisioning.Server
	RestoreModeSkip bool
	Callback        func(ctx context.Context, err error)
} {
	var calls []struct {
		Ctx             context.Context
		Server          provisioning.Server
		RestoreModeSkip bool
		Callback        func(ctx context.Context, err error)
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// SystemFactoryReset calls SystemFactoryResetFunc.
func (mock *ServerClientPortMock) SystemFactoryReset(ctx context.Context, endpoint provisioning.Endpoint, allowTPMResetFailure bool, seeds provisioning.TokenImageSeedConfigs, providerConfig api.TokenProviderConfig) error {
	if mock.SystemFactoryResetFunc == nil {
		panic("ServerClientPortMock.SystemFactoryResetFunc: method is nil but ServerClientPort.SystemFactoryReset was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		Endpoint             provisioning.Endpoint
		AllowTPMResetFailure bool
		Seeds                provisioning.TokenImageSeedConfigs
		ProviderConfig       api.TokenProviderConfig
	}{
		Ctx:                  ctx,
		Endpoint:             endpoint,
		AllowTPMResetFailure: allowTPMResetFailure,
		Seeds:                seeds,
		ProviderConfig:       providerConfig,
	}
	mock.lockSystemFactoryReset.Lock()
	mock.calls.SystemFactoryReset = append(mock.calls.SystemFactoryReset, callInfo)
	mock.lockSystemFactoryReset.Unlock()
	return mock.SystemFactoryResetFunc(ctx, endpoint, allowTPMResetFailure, seeds, providerConfig)
}

// SystemFactoryResetCalls gets all the calls that were made to SystemFactoryReset.
// Check the length with:
//
//	len(mockedServerClientPort.SystemFactoryResetCalls())
func (mock *ServerClientPortMock) SystemFactoryResetCalls() []struct {
	Ctx                  context.Context
	Endpoint             provisioning.Endpoint
	AllowTPMResetFailure bool
	Seeds                provisioning.TokenImageSeedConfigs
	ProviderConfig       api.TokenProviderConfig
} {
	var calls []struct {
		Ctx                  context.Context
		Endpoint             provisioning.Endpoint
		AllowTPMResetFailure bool
		Seeds                provisioning.TokenImageSeedConfigs
		ProviderConfig       api.TokenProviderConfig
	}
	mock.lockSystemFactoryReset.RLock()
	calls = mock.calls.SystemFactoryReset
	mock.lockSystemFactoryReset.RUnlock()
	return calls
}

// UpdateApplication calls UpdateApplicationFunc.
func (mock *ServerClientPortMock) UpdateApplication(ctx context.Context, server provisioning.Server, application string) error {
	if mock.UpdateApplicationFunc == nil {
		panic("ServerClientPortMock.UpdateApplicationFunc: method is nil but ServerClientPort.UpdateApplication was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}{
		Ctx:         ctx,
		Server:      server,
		Application: application,
	}
	mock.lockUpdateApplication.Lock()
	mock.calls.UpdateApplication = append(mock.calls.UpdateApplication, callInfo)
	mock.lockUpdateApplication.Unlock()
	return mock.UpdateApplicationFunc(ctx, server, application)
}

// UpdateApplicationCalls gets all the calls that were made to UpdateApplication.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateApplicationCalls())
func (mock *ServerClientPortMock) UpdateApplicationCalls() []struct {
	Ctx         context.Context
	Server      provisioning.Server
	Application string
} {
	var calls []struct {
		Ctx         context.Context
		Server      provisioning.Server
		Application string
	}
	mock.lockUpdateApplication.RLock()
	calls = mock.calls.UpdateApplication
	mock.lockUpdateApplication.RUnlock()
	return calls
}

// UpdateNetworkConfig calls UpdateNetworkConfigFunc.
func (mock *ServerClientPortMock) UpdateNetworkConfig(ctx context.Context, server provisioning.Server) error {
	if mock.UpdateNetworkConfigFunc == nil {
		panic("ServerClientPortMock.UpdateNetworkConfigFunc: method is nil but ServerClientPort.UpdateNetworkConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockUpdateNetworkConfig.Lock()
	mock.calls.UpdateNetworkConfig = append(mock.calls.UpdateNetworkConfig, callInfo)
	mock.lockUpdateNetworkConfig.Unlock()
	return mock.UpdateNetworkConfigFunc(ctx, server)
}

// UpdateNetworkConfigCalls gets all the calls that were made to UpdateNetworkConfig.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateNetworkConfigCalls())
func (mock *ServerClientPortMock) UpdateNetworkConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockUpdateNetworkConfig.RLock()
	calls = mock.calls.UpdateNetworkConfig
	mock.lockUpdateNetworkConfig.RUnlock()
	return calls
}

// UpdateOS calls UpdateOSFunc.
func (mock *ServerClientPortMock) UpdateOS(ctx context.Context, server provisioning.Server) error {
	if mock.UpdateOSFunc == nil {
		panic("ServerClientPortMock.UpdateOSFunc: method is nil but ServerClientPort.UpdateOS was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockUpdateOS.Lock()
	mock.calls.UpdateOS = append(mock.calls.UpdateOS, callInfo)
	mock.lockUpdateOS.Unlock()
	return mock.UpdateOSFunc(ctx, server)
}

// UpdateOSCalls gets all the calls that were made to UpdateOS.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateOSCalls())
func (mock *ServerClientPortMock) UpdateOSCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockUpdateOS.RLock()
	calls = mock.calls.UpdateOS
	mock.lockUpdateOS.RUnlock()
	return calls
}

// UpdateProviderConfig calls UpdateProviderConfigFunc.
func (mock *ServerClientPortMock) UpdateProviderConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemProvider) error {
	if mock.UpdateProviderConfigFunc == nil {
		panic("ServerClientPortMock.UpdateProviderConfigFunc: method is nil but ServerClientPort.UpdateProviderConfig was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Server         provisioning.Server
		ProviderConfig provisioning.ServerSystemProvider
	}{
		Ctx:            ctx,
		Server:         server,
		ProviderConfig: providerConfig,
	}
	mock.lockUpdateProviderConfig.Lock()
	mock.calls.UpdateProviderConfig = append(mock.calls.UpdateProviderConfig, callInfo)
	mock.lockUpdateProviderConfig.Unlock()
	return mock.UpdateProviderConfigFunc(ctx, server, providerConfig)
}

// UpdateProviderConfigCalls gets all the calls that were made to UpdateProviderConfig.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateProviderConfigCalls())
func (mock *ServerClientPortMock) UpdateProviderConfigCalls() []struct {
	Ctx            context.Context
	Server         provisioning.Server
	ProviderConfig provisioning.ServerSystemProvider
} {
	var calls []struct {
		Ctx            context.Context
		Server         provisioning.Server
		ProviderConfig provisioning.ServerSystemProvider
	}
	mock.lockUpdateProviderConfig.RLock()
	calls = mock.calls.UpdateProviderConfig
	mock.lockUpdateProviderConfig.RUnlock()
	return calls
}

// UpdateStorageConfig calls UpdateStorageConfigFunc.
func (mock *ServerClientPortMock) UpdateStorageConfig(ctx context.Context, server provisioning.Server) error {
	if mock.UpdateStorageConfigFunc == nil {
		panic("ServerClientPortMock.UpdateStorageConfigFunc: method is nil but ServerClientPort.UpdateStorageConfig was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
	}{
		Ctx:    ctx,
		Server: server,
	}
	mock.lockUpdateStorageConfig.Lock()
	mock.calls.UpdateStorageConfig = append(mock.calls.UpdateStorageConfig, callInfo)
	mock.lockUpdateStorageConfig.Unlock()
	return mock.UpdateStorageConfigFunc(ctx, server)
}

// UpdateStorageConfigCalls gets all the calls that were made to UpdateStorageConfig.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateStorageConfigCalls())
func (mock *ServerClientPortMock) UpdateStorageConfigCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
	}
	mock.lockUpdateStorageConfig.RLock()
	calls = mock.calls.UpdateStorageConfig
	mock.lockUpdateStorageConfig.RUnlock()
	return calls
}

// UpdateSystemKernel calls UpdateSystemKernelFunc.
func (mock *ServerClientPortMock) UpdateSystemKernel(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemKernel) error {
	if mock.UpdateSystemKernelFunc == nil {
		panic("ServerClientPortMock.UpdateSystemKernelFunc: method is nil but ServerClientPort.UpdateSystemKernel was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Config provisioning.ServerSystemKernel
	}{
		Ctx:    ctx,
		Server: server,
		Config: config,
	}
	mock.lockUpdateSystemKernel.Lock()
	mock.calls.UpdateSystemKernel = append(mock.calls.UpdateSystemKernel, callInfo)
	mock.lockUpdateSystemKernel.Unlock()
	return mock.UpdateSystemKernelFunc(ctx, server, config)
}

// UpdateSystemKernelCalls gets all the calls that were made to UpdateSystemKernel.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateSystemKernelCalls())
func (mock *ServerClientPortMock) UpdateSystemKernelCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Config provisioning.ServerSystemKernel
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Config provisioning.ServerSystemKernel
	}
	mock.lockUpdateSystemKernel.RLock()
	calls = mock.calls.UpdateSystemKernel
	mock.lockUpdateSystemKernel.RUnlock()
	return calls
}

// UpdateSystemLogging calls UpdateSystemLoggingFunc.
func (mock *ServerClientPortMock) UpdateSystemLogging(ctx context.Context, server provisioning.Server, config provisioning.ServerSystemLogging) error {
	if mock.UpdateSystemLoggingFunc == nil {
		panic("ServerClientPortMock.UpdateSystemLoggingFunc: method is nil but ServerClientPort.UpdateSystemLogging was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Server provisioning.Server
		Config provisioning.ServerSystemLogging
	}{
		Ctx:    ctx,
		Server: server,
		Config: config,
	}
	mock.lockUpdateSystemLogging.Lock()
	mock.calls.UpdateSystemLogging = append(mock.calls.UpdateSystemLogging, callInfo)
	mock.lockUpdateSystemLogging.Unlock()
	return mock.UpdateSystemLoggingFunc(ctx, server, config)
}

// UpdateSystemLoggingCalls gets all the calls that were made to UpdateSystemLogging.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateSystemLoggingCalls())
func (mock *ServerClientPortMock) UpdateSystemLoggingCalls() []struct {
	Ctx    context.Context
	Server provisioning.Server
	Config provisioning.ServerSystemLogging
} {
	var calls []struct {
		Ctx    context.Context
		Server provisioning.Server
		Config provisioning.ServerSystemLogging
	}
	mock.lockUpdateSystemLogging.RLock()
	calls = mock.calls.UpdateSystemLogging
	mock.lockUpdateSystemLogging.RUnlock()
	return calls
}

// UpdateUpdateConfig calls UpdateUpdateConfigFunc.
func (mock *ServerClientPortMock) UpdateUpdateConfig(ctx context.Context, server provisioning.Server, providerConfig provisioning.ServerSystemUpdate) error {
	if mock.UpdateUpdateConfigFunc == nil {
		panic("ServerClientPortMock.UpdateUpdateConfigFunc: method is nil but ServerClientPort.UpdateUpdateConfig was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Server         provisioning.Server
		ProviderConfig provisioning.ServerSystemUpdate
	}{
		Ctx:            ctx,
		Server:         server,
		ProviderConfig: providerConfig,
	}
	mock.lockUpdateUpdateConfig.Lock()
	mock.calls.UpdateUpdateConfig = append(mock.calls.UpdateUpdateConfig, callInfo)
	mock.lockUpdateUpdateConfig.Unlock()
	return mock.UpdateUpdateConfigFunc(ctx, server, providerConfig)
}

// UpdateUpdateConfigCalls gets all the calls that were made to UpdateUpdateConfig.
// Check the length with:
//
//	len(mockedServerClientPort.UpdateUpdateConfigCalls())
func (mock *ServerClientPortMock) UpdateUpdateConfigCalls() []struct {
	Ctx            context.Context
	Server         provisioning.Server
	ProviderConfig provisioning.ServerSystemUpdate
} {
	var calls []struct {
		Ctx            context.Context
		Server         provisioning.Server
		ProviderConfig provisioning.ServerSystemUpdate
	}
	mock.lockUpdateUpdateConfig.RLock()
	calls = mock.calls.UpdateUpdateConfig
	mock.lockUpdateUpdateConfig.RUnlock()
	return calls
}
