// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/system"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// componentProvisioningClusterService identifies the log records of this decorator and allows the
// log level to be configured for it individually.
var componentProvisioningClusterService = logger.RegisterComponent("system.provisioning_cluster_service")

// ProvisioningClusterServiceWithSlog implements system.ProvisioningClusterService that is instrumented with slog logger.
type ProvisioningClusterServiceWithSlog struct {
	_base      system.ProvisioningClusterService
	_component logger.Component
}

type ProvisioningClusterServiceWithSlogOption func(s *ProvisioningClusterServiceWithSlog)

// ProvisioningClusterServiceWithSlogWithComponent overrides the component this instance is
// attributed to. Use it to tell several instances of the same interface apart,
// e.g. the individual members of a chain.
func ProvisioningClusterServiceWithSlogWithComponent(component logger.Component) ProvisioningClusterServiceWithSlogOption {
	return func(_base *ProvisioningClusterServiceWithSlog) {
		_base._component = component
	}
}

// NewProvisioningClusterServiceWithSlog instruments an implementation of the system.ProvisioningClusterService with simple logging.
func NewProvisioningClusterServiceWithSlog(base system.ProvisioningClusterService, opts ...ProvisioningClusterServiceWithSlogOption) ProvisioningClusterServiceWithSlog {
	this := ProvisioningClusterServiceWithSlog{
		_base:      base,
		_component: componentProvisioningClusterService,
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// GetAll implements system.ProvisioningClusterService.
func (_d ProvisioningClusterServiceWithSlog) GetAll(ctx context.Context) (clusters provisioning.Clusters, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusters", clusters),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method GetAll returned an error")
		} else {
			log.DebugContext(ctx, "<= method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}
