// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"io"
	"log/slog"

	system0 "github.com/FuturFusion/operations-center/internal/system"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/shared/api/system"
)

// componentSystemService identifies the log records of this decorator and allows the
// log level to be configured for it individually.
var componentSystemService = logger.RegisterComponent("system.system_service")

// SystemServiceWithSlog implements system0.SystemService that is instrumented with slog logger.
type SystemServiceWithSlog struct {
	_base      system0.SystemService
	_component logger.Component
}

type SystemServiceWithSlogOption func(s *SystemServiceWithSlog)

// SystemServiceWithSlogWithComponent overrides the component this instance is
// attributed to. Use it to tell several instances of the same interface apart,
// e.g. the individual members of a chain.
func SystemServiceWithSlogWithComponent(component logger.Component) SystemServiceWithSlogOption {
	return func(_base *SystemServiceWithSlog) {
		_base._component = component
	}
}

// NewSystemServiceWithSlog instruments an implementation of the system0.SystemService with simple logging.
func NewSystemServiceWithSlog(base system0.SystemService, opts ...SystemServiceWithSlogOption) SystemServiceWithSlog {
	this := SystemServiceWithSlog{
		_base:      base,
		_component: componentSystemService,
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// Backup implements system0.SystemService.
func (_d SystemServiceWithSlog) Backup(ctx context.Context, complete bool) (readCloser io.ReadCloser, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Bool("complete", complete),
		)
	}
	log.DebugContext(ctx, "=> calling Backup")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("readCloser", readCloser),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Backup returned an error")
		} else {
			log.DebugContext(ctx, "<= method Backup finished")
		}
	}()
	return _d._base.Backup(ctx, complete)
}

// CleanCache implements system0.SystemService.
func (_d SystemServiceWithSlog) CleanCache(ctx context.Context) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling CleanCache")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method CleanCache returned an error")
		} else {
			log.DebugContext(ctx, "<= method CleanCache finished")
		}
	}()
	return _d._base.CleanCache(ctx)
}

// GetCertificate implements system0.SystemService.
func (_d SystemServiceWithSlog) GetCertificate(ctx context.Context) (certificate system.Certificate, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetCertificate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("certificate", certificate),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method GetCertificate returned an error")
		} else {
			log.DebugContext(ctx, "<= method GetCertificate finished")
		}
	}()
	return _d._base.GetCertificate(ctx)
}

// GetNetworkConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) GetNetworkConfig(ctx context.Context) (network system.Network) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetNetworkConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("network", network),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method GetNetworkConfig finished")
	}()
	return _d._base.GetNetworkConfig(ctx)
}

// GetSecurityConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) GetSecurityConfig(ctx context.Context) (security system.Security) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetSecurityConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("security", security),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method GetSecurityConfig finished")
	}()
	return _d._base.GetSecurityConfig(ctx)
}

// GetSettingsConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) GetSettingsConfig(ctx context.Context) (settings system.Settings) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetSettingsConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("settings", settings),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method GetSettingsConfig finished")
	}()
	return _d._base.GetSettingsConfig(ctx)
}

// GetUpdatesConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) GetUpdatesConfig(ctx context.Context) (updates system.Updates) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetUpdatesConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("updates", updates),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method GetUpdatesConfig finished")
	}()
	return _d._base.GetUpdatesConfig(ctx)
}

// Restore implements system0.SystemService.
func (_d SystemServiceWithSlog) Restore(ctx context.Context, archive io.Reader) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("archive", archive),
		)
	}
	log.DebugContext(ctx, "=> calling Restore")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Restore returned an error")
		} else {
			log.DebugContext(ctx, "<= method Restore finished")
		}
	}()
	return _d._base.Restore(ctx, archive)
}

// TriggerCertificateRenew implements system0.SystemService.
func (_d SystemServiceWithSlog) TriggerCertificateRenew(ctx context.Context, force bool) (changed bool, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling TriggerCertificateRenew")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Bool("changed", changed),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method TriggerCertificateRenew returned an error")
		} else {
			log.DebugContext(ctx, "<= method TriggerCertificateRenew finished")
		}
	}()
	return _d._base.TriggerCertificateRenew(ctx, force)
}

// UpdateCertificate implements system0.SystemService.
func (_d SystemServiceWithSlog) UpdateCertificate(ctx context.Context, certificatePEM string, keyPEM string) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("certificatePEM", certificatePEM),
			slog.String("keyPEM", keyPEM),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateCertificate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UpdateCertificate returned an error")
		} else {
			log.DebugContext(ctx, "<= method UpdateCertificate finished")
		}
	}()
	return _d._base.UpdateCertificate(ctx, certificatePEM, keyPEM)
}

// UpdateNetworkConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) UpdateNetworkConfig(ctx context.Context, cfg system.NetworkPut) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cfg", cfg),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateNetworkConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UpdateNetworkConfig returned an error")
		} else {
			log.DebugContext(ctx, "<= method UpdateNetworkConfig finished")
		}
	}()
	return _d._base.UpdateNetworkConfig(ctx, cfg)
}

// UpdateSecurityConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) UpdateSecurityConfig(ctx context.Context, cfg system.SecurityPut) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cfg", cfg),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSecurityConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UpdateSecurityConfig returned an error")
		} else {
			log.DebugContext(ctx, "<= method UpdateSecurityConfig finished")
		}
	}()
	return _d._base.UpdateSecurityConfig(ctx, cfg)
}

// UpdateSettingsConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) UpdateSettingsConfig(ctx context.Context, cfg system.SettingsPut) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cfg", cfg),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSettingsConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UpdateSettingsConfig returned an error")
		} else {
			log.DebugContext(ctx, "<= method UpdateSettingsConfig finished")
		}
	}()
	return _d._base.UpdateSettingsConfig(ctx, cfg)
}

// UpdateUpdatesConfig implements system0.SystemService.
func (_d SystemServiceWithSlog) UpdateUpdatesConfig(ctx context.Context, cfg system.UpdatesPut) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cfg", cfg),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateUpdatesConfig")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UpdateUpdatesConfig returned an error")
		} else {
			log.DebugContext(ctx, "<= method UpdateUpdatesConfig finished")
		}
	}()
	return _d._base.UpdateUpdatesConfig(ctx, cfg)
}
