// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"io"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	system0 "github.com/FuturFusion/operations-center/internal/system"
	"github.com/FuturFusion/operations-center/shared/api/system"
)

// SystemServiceWithPrometheus implements system0.SystemService interface with all methods wrapped
// with Prometheus metrics.
type SystemServiceWithPrometheus struct {
	base         system0.SystemService
	instanceName string
}

var systemServiceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "system_service_duration_seconds",
		Help:       "systemService runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewSystemServiceWithPrometheus returns an instance of the system0.SystemService decorated with prometheus summary metric.
func NewSystemServiceWithPrometheus(base system0.SystemService, instanceName string) SystemServiceWithPrometheus {
	return SystemServiceWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// Backup implements system0.SystemService.
func (_d SystemServiceWithPrometheus) Backup(ctx context.Context, complete bool) (readCloser io.ReadCloser, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Backup", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Backup(ctx, complete)
}

// CleanCache implements system0.SystemService.
func (_d SystemServiceWithPrometheus) CleanCache(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "CleanCache", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CleanCache(ctx)
}

// GetCertificate implements system0.SystemService.
func (_d SystemServiceWithPrometheus) GetCertificate(ctx context.Context) (certificate system.Certificate, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetCertificate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetCertificate(ctx)
}

// GetNetworkConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) GetNetworkConfig(ctx context.Context) (network system.Network) {
	_since := time.Now()
	defer func() {
		result := "ok"
		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetNetworkConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetNetworkConfig(ctx)
}

// GetSecurityConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) GetSecurityConfig(ctx context.Context) (security system.Security) {
	_since := time.Now()
	defer func() {
		result := "ok"
		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSecurityConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSecurityConfig(ctx)
}

// GetSettingsConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) GetSettingsConfig(ctx context.Context) (settings system.Settings) {
	_since := time.Now()
	defer func() {
		result := "ok"
		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSettingsConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSettingsConfig(ctx)
}

// GetUpdatesConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) GetUpdatesConfig(ctx context.Context) (updates system.Updates) {
	_since := time.Now()
	defer func() {
		result := "ok"
		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetUpdatesConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetUpdatesConfig(ctx)
}

// Restore implements system0.SystemService.
func (_d SystemServiceWithPrometheus) Restore(ctx context.Context, archive io.Reader) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Restore", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Restore(ctx, archive)
}

// TriggerCertificateRenew implements system0.SystemService.
func (_d SystemServiceWithPrometheus) TriggerCertificateRenew(ctx context.Context, force bool) (changed bool, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "TriggerCertificateRenew", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.TriggerCertificateRenew(ctx, force)
}

// UpdateCertificate implements system0.SystemService.
func (_d SystemServiceWithPrometheus) UpdateCertificate(ctx context.Context, certificatePEM string, keyPEM string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateCertificate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateCertificate(ctx, certificatePEM, keyPEM)
}

// UpdateNetworkConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) UpdateNetworkConfig(ctx context.Context, cfg system.NetworkPut) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateNetworkConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateNetworkConfig(ctx, cfg)
}

// UpdateSecurityConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) UpdateSecurityConfig(ctx context.Context, cfg system.SecurityPut) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSecurityConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSecurityConfig(ctx, cfg)
}

// UpdateSettingsConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) UpdateSettingsConfig(ctx context.Context, cfg system.SettingsPut) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSettingsConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSettingsConfig(ctx, cfg)
}

// UpdateUpdatesConfig implements system0.SystemService.
func (_d SystemServiceWithPrometheus) UpdateUpdatesConfig(ctx context.Context, cfg system.UpdatesPut) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		systemServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateUpdatesConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateUpdatesConfig(ctx, cfg)
}
