// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkAddressSets(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.NetworkAddressSet, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverNetworkAddressSets, err := client.GetNetworkAddressSetsAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkAddressSets, nil
}

func (c Client) GetNetworkAddressSetByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkAddressSetName string) (incusapi.NetworkAddressSet, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkAddressSet{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkAddressSet, _, err := client.GetNetworkAddressSet(networkAddressSetName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkAddressSet{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkAddressSet{}, err
	}

	return *serverNetworkAddressSet, nil
}
