// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkLoadBalancers(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string) ([]incusapi.NetworkLoadBalancer, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	client = client.UseProject(projectName)

	serverNetworkLoadBalancers, err := client.GetNetworkLoadBalancers(networkName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkLoadBalancers, nil
}

func (c Client) GetNetworkLoadBalancerByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string, networkLoadBalancerName string) (incusapi.NetworkLoadBalancer, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkLoadBalancer{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkLoadBalancer, _, err := client.GetNetworkLoadBalancer(networkName, networkLoadBalancerName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkLoadBalancer{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkLoadBalancer{}, err
	}

	return *serverNetworkLoadBalancer, nil
}
