// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkForwards(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string) ([]incusapi.NetworkForward, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	client = client.UseProject(projectName)

	serverNetworkForwards, err := client.GetNetworkForwards(networkName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkForwards, nil
}

func (c Client) GetNetworkForwardByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string, networkForwardName string) (incusapi.NetworkForward, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkForward{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkForward, _, err := client.GetNetworkForward(networkName, networkForwardName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkForward{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkForward{}, err
	}

	return *serverNetworkForward, nil
}
