// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkPeers(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string) ([]incusapi.NetworkPeer, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	client = client.UseProject(projectName)

	serverNetworkPeers, err := client.GetNetworkPeers(networkName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkPeers, nil
}

func (c Client) GetNetworkPeerByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string, networkPeerName string) (incusapi.NetworkPeer, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkPeer{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkPeer, _, err := client.GetNetworkPeer(networkName, networkPeerName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkPeer{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkPeer{}, err
	}

	return *serverNetworkPeer, nil
}
