// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworks(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.Network, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverNetworks, err := client.GetNetworksAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworks, nil
}

func (c Client) GetNetworkByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkName string) (incusapi.Network, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.Network{}, err
	}

	client = client.UseProject(projectName)

	serverNetwork, _, err := client.GetNetwork(networkName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.Network{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.Network{}, err
	}

	return *serverNetwork, nil
}
