// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetProjects(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.Project, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverProjects, err := client.GetProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverProjects, nil
}

func (c Client) GetProjectByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string) (incusapi.Project, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.Project{}, err
	}

	serverProject, _, err := client.GetProject(projectName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.Project{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.Project{}, err
	}

	return *serverProject, nil
}
