// Code generated by generate-inventory; DO NOT EDIT.

package incus_test

import (
	"context"
	"net/http"
	"testing"

	incusapi "github.com/lxc/incus/v7/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/adapter/incus"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/testing/queue"
	"github.com/FuturFusion/operations-center/shared/api"
)

func networkPeerClientTestCases(t *testing.T) []methodTestSet {
	return []methodTestSet{
		{
			name:            "GetNetworkPeers",
			wantPathsPrefix: true,
			clientCall: func(ctx context.Context, client incus.Client, server provisioning.Server) (any, error) {
				return client.GetNetworkPeers(ctx, server, "project", "network")
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: []incusapi.NetworkPeer{
										{
											Name: "networkPeer one",
										},
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()
						require.Len(t, res, 1)
					},
					wantPaths: []string{"GET /1.0/networks/network/peers?"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:       api.ErrorResponse,
									StatusCode: http.StatusNotFound,
								},
								),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/networks/network/peers?"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/networks/network/peers?"},
				},
			},
		},

		{
			name:            "GetNetworkPeerByName",
			wantPathsPrefix: true,
			clientCall: func(ctx context.Context, client incus.Client, server provisioning.Server) (any, error) {
				return client.GetNetworkPeerByName(ctx, server, "project", "network", "name")
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: incusapi.NetworkPeer{
										Name: "networkPeer one",
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()

						wantNetworkPeer := incusapi.NetworkPeer{
							Name: "networkPeer one",
						}

						require.Equal(t, wantNetworkPeer, res)
					},
					wantPaths: []string{"GET /1.0/networks/network/peers/name"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/networks/network/peers/name"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:   api.ErrorResponse,
									Status: http.StatusText(http.StatusNotFound),
								}),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/networks/network/peers/name"},
				},
			},
		},
	}
}
