// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetInstances(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.InstanceFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverInstances, err := client.GetInstancesFullAllProjects(incusapi.InstanceTypeAny)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverInstances, nil
}

func (c Client) GetInstanceByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, instanceName string) (incusapi.InstanceFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.InstanceFull{}, err
	}

	client = client.UseProject(projectName)

	serverInstance, _, err := client.GetInstanceFull(instanceName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.InstanceFull{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.InstanceFull{}, err
	}

	return *serverInstance, nil
}
