// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetImages(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.Image, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverImages, err := client.GetImagesAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverImages, nil
}

func (c Client) GetImageByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, imageName string) (incusapi.Image, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.Image{}, err
	}

	client = client.UseProject(projectName)

	serverImage, _, err := client.GetImage(imageName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.Image{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.Image{}, err
	}

	return *serverImage, nil
}
