// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkIntegrations(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.NetworkIntegration, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverNetworkIntegrations, err := client.GetNetworkIntegrations()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkIntegrations, nil
}

func (c Client) GetNetworkIntegrationByName(ctx context.Context, endpoint provisioning.Endpoint, networkIntegrationName string) (incusapi.NetworkIntegration, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkIntegration{}, err
	}

	serverNetworkIntegration, _, err := client.GetNetworkIntegration(networkIntegrationName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkIntegration{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkIntegration{}, err
	}

	return *serverNetworkIntegration, nil
}
