// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkACLs(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.NetworkACL, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverNetworkACLs, err := client.GetNetworkACLsAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkACLs, nil
}

func (c Client) GetNetworkACLByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkACLName string) (incusapi.NetworkACL, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkACL{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkACL, _, err := client.GetNetworkACL(networkACLName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkACL{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkACL{}, err
	}

	return *serverNetworkACL, nil
}
