// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetNetworkZones(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.NetworkZone, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverNetworkZones, err := client.GetNetworkZonesAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverNetworkZones, nil
}

func (c Client) GetNetworkZoneByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkZoneName string) (incusapi.NetworkZone, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.NetworkZone{}, err
	}

	client = client.UseProject(projectName)

	serverNetworkZone, _, err := client.GetNetworkZone(networkZoneName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.NetworkZone{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.NetworkZone{}, err
	}

	return *serverNetworkZone, nil
}
