// Code generated by generate-inventory; DO NOT EDIT.

package incus_test

import "testing"

func appendTestCases(t *testing.T, methods []methodTestSet) []methodTestSet {
	methods = append(methods, imageClientTestCases(t)...)
	methods = append(methods, instanceClientTestCases(t)...)
	methods = append(methods, networkClientTestCases(t)...)
	methods = append(methods, networkACLClientTestCases(t)...)
	methods = append(methods, networkAddressSetClientTestCases(t)...)
	methods = append(methods, networkForwardClientTestCases(t)...)
	methods = append(methods, networkIntegrationClientTestCases(t)...)
	methods = append(methods, networkLoadBalancerClientTestCases(t)...)
	methods = append(methods, networkPeerClientTestCases(t)...)
	methods = append(methods, networkZoneClientTestCases(t)...)
	methods = append(methods, profileClientTestCases(t)...)
	methods = append(methods, projectClientTestCases(t)...)
	methods = append(methods, storageBucketClientTestCases(t)...)
	methods = append(methods, storagePoolClientTestCases(t)...)
	methods = append(methods, storageVolumeClientTestCases(t)...)

	return methods
}
