// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetStorageBuckets(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string) ([]incusapi.StorageBucketFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverStorageBuckets, err := client.GetStoragePoolBucketsFullAllProjects(storagePoolName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverStorageBuckets, nil
}

func (c Client) GetStorageBucketByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, storagePoolName string, storageBucketName string) (incusapi.StorageBucketFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.StorageBucketFull{}, err
	}

	client = client.UseProject(projectName)

	serverStorageBucket, _, err := client.GetStoragePoolBucketFull(storagePoolName, storageBucketName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.StorageBucketFull{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.StorageBucketFull{}, err
	}

	return *serverStorageBucket, nil
}
