// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetStoragePools(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.StoragePool, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverStoragePools, err := client.GetStoragePools()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverStoragePools, nil
}

func (c Client) GetStoragePoolByName(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string) (incusapi.StoragePool, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.StoragePool{}, err
	}

	serverStoragePool, _, err := client.GetStoragePool(storagePoolName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.StoragePool{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.StoragePool{}, err
	}

	return *serverStoragePool, nil
}
