// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetStorageVolumes(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string) ([]incusapi.StorageVolumeFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverStorageVolumes, err := client.GetStoragePoolVolumesFullAllProjects(storagePoolName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverStorageVolumes, nil
}

func (c Client) GetStorageVolumeByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, storagePoolName string, storageVolumeName string, storageVolumeType string) (incusapi.StorageVolumeFull, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.StorageVolumeFull{}, err
	}

	client = client.UseProject(projectName)

	serverStorageVolume, _, err := client.GetStoragePoolVolumeFull(storagePoolName, storageVolumeType, storageVolumeName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.StorageVolumeFull{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.StorageVolumeFull{}, err
	}

	return *serverStorageVolume, nil
}
