// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"
	"net/http"

	incusapi "github.com/lxc/incus/v7/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

func (c Client) GetProfiles(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.Profile, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return nil, err
	}

	serverProfiles, err := client.GetProfilesAllProjects()
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return nil, domain.ErrNotFound
	}

	if err != nil {
		return nil, err
	}

	return serverProfiles, nil
}

func (c Client) GetProfileByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, profileName string) (incusapi.Profile, error) {
	client, err := c.getClient(ctx, endpoint)
	if err != nil {
		return incusapi.Profile{}, err
	}

	client = client.UseProject(projectName)

	serverProfile, _, err := client.GetProfile(profileName)
	if incusapi.StatusErrorCheck(err, http.StatusNotFound) {
		return incusapi.Profile{}, domain.ErrNotFound
	}

	if err != nil {
		return incusapi.Profile{}, err
	}

	return *serverProfile, nil
}
