// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/system"
)

// Ensure that ProvisioningClusterServiceMock does implement system.ProvisioningClusterService.
// If this is not the case, regenerate this file with mockery.
var _ system.ProvisioningClusterService = &ProvisioningClusterServiceMock{}

// ProvisioningClusterServiceMock is a mock implementation of system.ProvisioningClusterService.
//
//	func TestSomethingThatUsesProvisioningClusterService(t *testing.T) {
//
//		// make and configure a mocked system.ProvisioningClusterService
//		mockedProvisioningClusterService := &ProvisioningClusterServiceMock{
//			GetAllFunc: func(ctx context.Context) (provisioning.Clusters, error) {
//				panic("mock out the GetAll method")
//			},
//		}
//
//		// use mockedProvisioningClusterService in code that requires system.ProvisioningClusterService
//		// and then make assertions.
//
//	}
type ProvisioningClusterServiceMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (provisioning.Clusters, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetAll sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *ProvisioningClusterServiceMock) GetAll(ctx context.Context) (provisioning.Clusters, error) {
	if mock.GetAllFunc == nil {
		panic("ProvisioningClusterServiceMock.GetAllFunc: method is nil but ProvisioningClusterService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedProvisioningClusterService.GetAllCalls())
func (mock *ProvisioningClusterServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}
