// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"io"
	"sync"

	system0 "github.com/FuturFusion/operations-center/internal/system"
	"github.com/FuturFusion/operations-center/shared/api/system"
)

// Ensure that SystemServiceMock does implement system0.SystemService.
// If this is not the case, regenerate this file with mockery.
var _ system0.SystemService = &SystemServiceMock{}

// SystemServiceMock is a mock implementation of system0.SystemService.
//
//	func TestSomethingThatUsesSystemService(t *testing.T) {
//
//		// make and configure a mocked system0.SystemService
//		mockedSystemService := &SystemServiceMock{
//			BackupFunc: func(ctx context.Context, complete bool) (io.ReadCloser, error) {
//				panic("mock out the Backup method")
//			},
//			CleanCacheFunc: func(ctx context.Context) error {
//				panic("mock out the CleanCache method")
//			},
//			GetCertificateFunc: func(ctx context.Context) (system.Certificate, error) {
//				panic("mock out the GetCertificate method")
//			},
//			GetNetworkConfigFunc: func(ctx context.Context) system.Network {
//				panic("mock out the GetNetworkConfig method")
//			},
//			GetSecurityConfigFunc: func(ctx context.Context) system.Security {
//				panic("mock out the GetSecurityConfig method")
//			},
//			GetSettingsConfigFunc: func(ctx context.Context) system.Settings {
//				panic("mock out the GetSettingsConfig method")
//			},
//			GetUpdatesConfigFunc: func(ctx context.Context) system.Updates {
//				panic("mock out the GetUpdatesConfig method")
//			},
//			RestoreFunc: func(ctx context.Context, archive io.Reader) error {
//				panic("mock out the Restore method")
//			},
//			TriggerCertificateRenewFunc: func(ctx context.Context, force bool) (bool, error) {
//				panic("mock out the TriggerCertificateRenew method")
//			},
//			UpdateCertificateFunc: func(ctx context.Context, certificatePEM string, keyPEM string) error {
//				panic("mock out the UpdateCertificate method")
//			},
//			UpdateNetworkConfigFunc: func(ctx context.Context, cfg system.NetworkPut) error {
//				panic("mock out the UpdateNetworkConfig method")
//			},
//			UpdateSecurityConfigFunc: func(ctx context.Context, cfg system.SecurityPut) error {
//				panic("mock out the UpdateSecurityConfig method")
//			},
//			UpdateSettingsConfigFunc: func(ctx context.Context, cfg system.SettingsPut) error {
//				panic("mock out the UpdateSettingsConfig method")
//			},
//			UpdateUpdatesConfigFunc: func(ctx context.Context, cfg system.UpdatesPut) error {
//				panic("mock out the UpdateUpdatesConfig method")
//			},
//		}
//
//		// use mockedSystemService in code that requires system0.SystemService
//		// and then make assertions.
//
//	}
type SystemServiceMock struct {
	// BackupFunc mocks the Backup method.
	BackupFunc func(ctx context.Context, complete bool) (io.ReadCloser, error)

	// CleanCacheFunc mocks the CleanCache method.
	CleanCacheFunc func(ctx context.Context) error

	// GetCertificateFunc mocks the GetCertificate method.
	GetCertificateFunc func(ctx context.Context) (system.Certificate, error)

	// GetNetworkConfigFunc mocks the GetNetworkConfig method.
	GetNetworkConfigFunc func(ctx context.Context) system.Network

	// GetSecurityConfigFunc mocks the GetSecurityConfig method.
	GetSecurityConfigFunc func(ctx context.Context) system.Security

	// GetSettingsConfigFunc mocks the GetSettingsConfig method.
	GetSettingsConfigFunc func(ctx context.Context) system.Settings

	// GetUpdatesConfigFunc mocks the GetUpdatesConfig method.
	GetUpdatesConfigFunc func(ctx context.Context) system.Updates

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, archive io.Reader) error

	// TriggerCertificateRenewFunc mocks the TriggerCertificateRenew method.
	TriggerCertificateRenewFunc func(ctx context.Context, force bool) (bool, error)

	// UpdateCertificateFunc mocks the UpdateCertificate method.
	UpdateCertificateFunc func(ctx context.Context, certificatePEM string, keyPEM string) error

	// UpdateNetworkConfigFunc mocks the UpdateNetworkConfig method.
	UpdateNetworkConfigFunc func(ctx context.Context, cfg system.NetworkPut) error

	// UpdateSecurityConfigFunc mocks the UpdateSecurityConfig method.
	UpdateSecurityConfigFunc func(ctx context.Context, cfg system.SecurityPut) error

	// UpdateSettingsConfigFunc mocks the UpdateSettingsConfig method.
	UpdateSettingsConfigFunc func(ctx context.Context, cfg system.SettingsPut) error

	// UpdateUpdatesConfigFunc mocks the UpdateUpdatesConfig method.
	UpdateUpdatesConfigFunc func(ctx context.Context, cfg system.UpdatesPut) error

	// calls tracks calls to the methods.
	calls struct {
		// Backup holds details about calls to the Backup method.
		Backup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Complete is the complete argument value.
			Complete bool
		}
		// CleanCache holds details about calls to the CleanCache method.
		CleanCache []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetCertificate holds details about calls to the GetCertificate method.
		GetCertificate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetNetworkConfig holds details about calls to the GetNetworkConfig method.
		GetNetworkConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSecurityConfig holds details about calls to the GetSecurityConfig method.
		GetSecurityConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSettingsConfig holds details about calls to the GetSettingsConfig method.
		GetSettingsConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetUpdatesConfig holds details about calls to the GetUpdatesConfig method.
		GetUpdatesConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Archive is the archive argument value.
			Archive io.Reader
		}
		// TriggerCertificateRenew holds details about calls to the TriggerCertificateRenew method.
		TriggerCertificateRenew []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Force is the force argument value.
			Force bool
		}
		// UpdateCertificate holds details about calls to the UpdateCertificate method.
		UpdateCertificate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CertificatePEM is the certificatePEM argument value.
			CertificatePEM string
			// KeyPEM is the keyPEM argument value.
			KeyPEM string
		}
		// UpdateNetworkConfig holds details about calls to the UpdateNetworkConfig method.
		UpdateNetworkConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg system.NetworkPut
		}
		// UpdateSecurityConfig holds details about calls to the UpdateSecurityConfig method.
		UpdateSecurityConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg system.SecurityPut
		}
		// UpdateSettingsConfig holds details about calls to the UpdateSettingsConfig method.
		UpdateSettingsConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg system.SettingsPut
		}
		// UpdateUpdatesConfig holds details about calls to the UpdateUpdatesConfig method.
		UpdateUpdatesConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg system.UpdatesPut
		}
	}
	lockBackup                  sync.RWMutex
	lockCleanCache              sync.RWMutex
	lockGetCertificate          sync.RWMutex
	lockGetNetworkConfig        sync.RWMutex
	lockGetSecurityConfig       sync.RWMutex
	lockGetSettingsConfig       sync.RWMutex
	lockGetUpdatesConfig        sync.RWMutex
	lockRestore                 sync.RWMutex
	lockTriggerCertificateRenew sync.RWMutex
	lockUpdateCertificate       sync.RWMutex
	lockUpdateNetworkConfig     sync.RWMutex
	lockUpdateSecurityConfig    sync.RWMutex
	lockUpdateSettingsConfig    sync.RWMutex
	lockUpdateUpdatesConfig     sync.RWMutex
}

// Backup calls BackupFunc.
func (mock *SystemServiceMock) Backup(ctx context.Context, complete bool) (io.ReadCloser, error) {
	if mock.BackupFunc == nil {
		panic("SystemServiceMock.BackupFunc: method is nil but SystemService.Backup was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Complete bool
	}{
		Ctx:      ctx,
		Complete: complete,
	}
	mock.lockBackup.Lock()
	mock.calls.Backup = append(mock.calls.Backup, callInfo)
	mock.lockBackup.Unlock()
	return mock.BackupFunc(ctx, complete)
}

// BackupCalls gets all the calls that were made to Backup.
// Check the length with:
//
//	len(mockedSystemService.BackupCalls())
func (mock *SystemServiceMock) BackupCalls() []struct {
	Ctx      context.Context
	Complete bool
} {
	var calls []struct {
		Ctx      context.Context
		Complete bool
	}
	mock.lockBackup.RLock()
	calls = mock.calls.Backup
	mock.lockBackup.RUnlock()
	return calls
}

// CleanCache calls CleanCacheFunc.
func (mock *SystemServiceMock) CleanCache(ctx context.Context) error {
	if mock.CleanCacheFunc == nil {
		panic("SystemServiceMock.CleanCacheFunc: method is nil but SystemService.CleanCache was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCleanCache.Lock()
	mock.calls.CleanCache = append(mock.calls.CleanCache, callInfo)
	mock.lockCleanCache.Unlock()
	return mock.CleanCacheFunc(ctx)
}

// CleanCacheCalls gets all the calls that were made to CleanCache.
// Check the length with:
//
//	len(mockedSystemService.CleanCacheCalls())
func (mock *SystemServiceMock) CleanCacheCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCleanCache.RLock()
	calls = mock.calls.CleanCache
	mock.lockCleanCache.RUnlock()
	return calls
}

// GetCertificate calls GetCertificateFunc.
func (mock *SystemServiceMock) GetCertificate(ctx context.Context) (system.Certificate, error) {
	if mock.GetCertificateFunc == nil {
		panic("SystemServiceMock.GetCertificateFunc: method is nil but SystemService.GetCertificate was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetCertificate.Lock()
	mock.calls.GetCertificate = append(mock.calls.GetCertificate, callInfo)
	mock.lockGetCertificate.Unlock()
	return mock.GetCertificateFunc(ctx)
}

// GetCertificateCalls gets all the calls that were made to GetCertificate.
// Check the length with:
//
//	len(mockedSystemService.GetCertificateCalls())
func (mock *SystemServiceMock) GetCertificateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetCertificate.RLock()
	calls = mock.calls.GetCertificate
	mock.lockGetCertificate.RUnlock()
	return calls
}

// GetNetworkConfig calls GetNetworkConfigFunc.
func (mock *SystemServiceMock) GetNetworkConfig(ctx context.Context) system.Network {
	if mock.GetNetworkConfigFunc == nil {
		panic("SystemServiceMock.GetNetworkConfigFunc: method is nil but SystemService.GetNetworkConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetNetworkConfig.Lock()
	mock.calls.GetNetworkConfig = append(mock.calls.GetNetworkConfig, callInfo)
	mock.lockGetNetworkConfig.Unlock()
	return mock.GetNetworkConfigFunc(ctx)
}

// GetNetworkConfigCalls gets all the calls that were made to GetNetworkConfig.
// Check the length with:
//
//	len(mockedSystemService.GetNetworkConfigCalls())
func (mock *SystemServiceMock) GetNetworkConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetNetworkConfig.RLock()
	calls = mock.calls.GetNetworkConfig
	mock.lockGetNetworkConfig.RUnlock()
	return calls
}

// GetSecurityConfig calls GetSecurityConfigFunc.
func (mock *SystemServiceMock) GetSecurityConfig(ctx context.Context) system.Security {
	if mock.GetSecurityConfigFunc == nil {
		panic("SystemServiceMock.GetSecurityConfigFunc: method is nil but SystemService.GetSecurityConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSecurityConfig.Lock()
	mock.calls.GetSecurityConfig = append(mock.calls.GetSecurityConfig, callInfo)
	mock.lockGetSecurityConfig.Unlock()
	return mock.GetSecurityConfigFunc(ctx)
}

// GetSecurityConfigCalls gets all the calls that were made to GetSecurityConfig.
// Check the length with:
//
//	len(mockedSystemService.GetSecurityConfigCalls())
func (mock *SystemServiceMock) GetSecurityConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSecurityConfig.RLock()
	calls = mock.calls.GetSecurityConfig
	mock.lockGetSecurityConfig.RUnlock()
	return calls
}

// GetSettingsConfig calls GetSettingsConfigFunc.
func (mock *SystemServiceMock) GetSettingsConfig(ctx context.Context) system.Settings {
	if mock.GetSettingsConfigFunc == nil {
		panic("SystemServiceMock.GetSettingsConfigFunc: method is nil but SystemService.GetSettingsConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettingsConfig.Lock()
	mock.calls.GetSettingsConfig = append(mock.calls.GetSettingsConfig, callInfo)
	mock.lockGetSettingsConfig.Unlock()
	return mock.GetSettingsConfigFunc(ctx)
}

// GetSettingsConfigCalls gets all the calls that were made to GetSettingsConfig.
// Check the length with:
//
//	len(mockedSystemService.GetSettingsConfigCalls())
func (mock *SystemServiceMock) GetSettingsConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettingsConfig.RLock()
	calls = mock.calls.GetSettingsConfig
	mock.lockGetSettingsConfig.RUnlock()
	return calls
}

// GetUpdatesConfig calls GetUpdatesConfigFunc.
func (mock *SystemServiceMock) GetUpdatesConfig(ctx context.Context) system.Updates {
	if mock.GetUpdatesConfigFunc == nil {
		panic("SystemServiceMock.GetUpdatesConfigFunc: method is nil but SystemService.GetUpdatesConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetUpdatesConfig.Lock()
	mock.calls.GetUpdatesConfig = append(mock.calls.GetUpdatesConfig, callInfo)
	mock.lockGetUpdatesConfig.Unlock()
	return mock.GetUpdatesConfigFunc(ctx)
}

// GetUpdatesConfigCalls gets all the calls that were made to GetUpdatesConfig.
// Check the length with:
//
//	len(mockedSystemService.GetUpdatesConfigCalls())
func (mock *SystemServiceMock) GetUpdatesConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetUpdatesConfig.RLock()
	calls = mock.calls.GetUpdatesConfig
	mock.lockGetUpdatesConfig.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *SystemServiceMock) Restore(ctx context.Context, archive io.Reader) error {
	if mock.RestoreFunc == nil {
		panic("SystemServiceMock.RestoreFunc: method is nil but SystemService.Restore was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Archive io.Reader
	}{
		Ctx:     ctx,
		Archive: archive,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, archive)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedSystemService.RestoreCalls())
func (mock *SystemServiceMock) RestoreCalls() []struct {
	Ctx     context.Context
	Archive io.Reader
} {
	var calls []struct {
		Ctx     context.Context
		Archive io.Reader
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// TriggerCertificateRenew calls TriggerCertificateRenewFunc.
func (mock *SystemServiceMock) TriggerCertificateRenew(ctx context.Context, force bool) (bool, error) {
	if mock.TriggerCertificateRenewFunc == nil {
		panic("SystemServiceMock.TriggerCertificateRenewFunc: method is nil but SystemService.TriggerCertificateRenew was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Force bool
	}{
		Ctx:   ctx,
		Force: force,
	}
	mock.lockTriggerCertificateRenew.Lock()
	mock.calls.TriggerCertificateRenew = append(mock.calls.TriggerCertificateRenew, callInfo)
	mock.lockTriggerCertificateRenew.Unlock()
	return mock.TriggerCertificateRenewFunc(ctx, force)
}

// TriggerCertificateRenewCalls gets all the calls that were made to TriggerCertificateRenew.
// Check the length with:
//
//	len(mockedSystemService.TriggerCertificateRenewCalls())
func (mock *SystemServiceMock) TriggerCertificateRenewCalls() []struct {
	Ctx   context.Context
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Force bool
	}
	mock.lockTriggerCertificateRenew.RLock()
	calls = mock.calls.TriggerCertificateRenew
	mock.lockTriggerCertificateRenew.RUnlock()
	return calls
}

// UpdateCertificate calls UpdateCertificateFunc.
func (mock *SystemServiceMock) UpdateCertificate(ctx context.Context, certificatePEM string, keyPEM string) error {
	if mock.UpdateCertificateFunc == nil {
		panic("SystemServiceMock.UpdateCertificateFunc: method is nil but SystemService.UpdateCertificate was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CertificatePEM string
		KeyPEM         string
	}{
		Ctx:            ctx,
		CertificatePEM: certificatePEM,
		KeyPEM:         keyPEM,
	}
	mock.lockUpdateCertificate.Lock()
	mock.calls.UpdateCertificate = append(mock.calls.UpdateCertificate, callInfo)
	mock.lockUpdateCertificate.Unlock()
	return mock.UpdateCertificateFunc(ctx, certificatePEM, keyPEM)
}

// UpdateCertificateCalls gets all the calls that were made to UpdateCertificate.
// Check the length with:
//
//	len(mockedSystemService.UpdateCertificateCalls())
func (mock *SystemServiceMock) UpdateCertificateCalls() []struct {
	Ctx            context.Context
	CertificatePEM string
	KeyPEM         string
} {
	var calls []struct {
		Ctx            context.Context
		CertificatePEM string
		KeyPEM         string
	}
	mock.lockUpdateCertificate.RLock()
	calls = mock.calls.UpdateCertificate
	mock.lockUpdateCertificate.RUnlock()
	return calls
}

// UpdateNetworkConfig calls UpdateNetworkConfigFunc.
func (mock *SystemServiceMock) UpdateNetworkConfig(ctx context.Context, cfg system.NetworkPut) error {
	if mock.UpdateNetworkConfigFunc == nil {
		panic("SystemServiceMock.UpdateNetworkConfigFunc: method is nil but SystemService.UpdateNetworkConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg system.NetworkPut
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockUpdateNetworkConfig.Lock()
	mock.calls.UpdateNetworkConfig = append(mock.calls.UpdateNetworkConfig, callInfo)
	mock.lockUpdateNetworkConfig.Unlock()
	return mock.UpdateNetworkConfigFunc(ctx, cfg)
}

// UpdateNetworkConfigCalls gets all the calls that were made to UpdateNetworkConfig.
// Check the length with:
//
//	len(mockedSystemService.UpdateNetworkConfigCalls())
func (mock *SystemServiceMock) UpdateNetworkConfigCalls() []struct {
	Ctx context.Context
	Cfg system.NetworkPut
} {
	var calls []struct {
		Ctx context.Context
		Cfg system.NetworkPut
	}
	mock.lockUpdateNetworkConfig.RLock()
	calls = mock.calls.UpdateNetworkConfig
	mock.lockUpdateNetworkConfig.RUnlock()
	return calls
}

// UpdateSecurityConfig calls UpdateSecurityConfigFunc.
func (mock *SystemServiceMock) UpdateSecurityConfig(ctx context.Context, cfg system.SecurityPut) error {
	if mock.UpdateSecurityConfigFunc == nil {
		panic("SystemServiceMock.UpdateSecurityConfigFunc: method is nil but SystemService.UpdateSecurityConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg system.SecurityPut
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockUpdateSecurityConfig.Lock()
	mock.calls.UpdateSecurityConfig = append(mock.calls.UpdateSecurityConfig, callInfo)
	mock.lockUpdateSecurityConfig.Unlock()
	return mock.UpdateSecurityConfigFunc(ctx, cfg)
}

// UpdateSecurityConfigCalls gets all the calls that were made to UpdateSecurityConfig.
// Check the length with:
//
//	len(mockedSystemService.UpdateSecurityConfigCalls())
func (mock *SystemServiceMock) UpdateSecurityConfigCalls() []struct {
	Ctx context.Context
	Cfg system.SecurityPut
} {
	var calls []struct {
		Ctx context.Context
		Cfg system.SecurityPut
	}
	mock.lockUpdateSecurityConfig.RLock()
	calls = mock.calls.UpdateSecurityConfig
	mock.lockUpdateSecurityConfig.RUnlock()
	return calls
}

// UpdateSettingsConfig calls UpdateSettingsConfigFunc.
func (mock *SystemServiceMock) UpdateSettingsConfig(ctx context.Context, cfg system.SettingsPut) error {
	if mock.UpdateSettingsConfigFunc == nil {
		panic("SystemServiceMock.UpdateSettingsConfigFunc: method is nil but SystemService.UpdateSettingsConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg system.SettingsPut
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockUpdateSettingsConfig.Lock()
	mock.calls.UpdateSettingsConfig = append(mock.calls.UpdateSettingsConfig, callInfo)
	mock.lockUpdateSettingsConfig.Unlock()
	return mock.UpdateSettingsConfigFunc(ctx, cfg)
}

// UpdateSettingsConfigCalls gets all the calls that were made to UpdateSettingsConfig.
// Check the length with:
//
//	len(mockedSystemService.UpdateSettingsConfigCalls())
func (mock *SystemServiceMock) UpdateSettingsConfigCalls() []struct {
	Ctx context.Context
	Cfg system.SettingsPut
} {
	var calls []struct {
		Ctx context.Context
		Cfg system.SettingsPut
	}
	mock.lockUpdateSettingsConfig.RLock()
	calls = mock.calls.UpdateSettingsConfig
	mock.lockUpdateSettingsConfig.RUnlock()
	return calls
}

// UpdateUpdatesConfig calls UpdateUpdatesConfigFunc.
func (mock *SystemServiceMock) UpdateUpdatesConfig(ctx context.Context, cfg system.UpdatesPut) error {
	if mock.UpdateUpdatesConfigFunc == nil {
		panic("SystemServiceMock.UpdateUpdatesConfigFunc: method is nil but SystemService.UpdateUpdatesConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg system.UpdatesPut
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockUpdateUpdatesConfig.Lock()
	mock.calls.UpdateUpdatesConfig = append(mock.calls.UpdateUpdatesConfig, callInfo)
	mock.lockUpdateUpdatesConfig.Unlock()
	return mock.UpdateUpdatesConfigFunc(ctx, cfg)
}

// UpdateUpdatesConfigCalls gets all the calls that were made to UpdateUpdatesConfig.
// Check the length with:
//
//	len(mockedSystemService.UpdateUpdatesConfigCalls())
func (mock *SystemServiceMock) UpdateUpdatesConfigCalls() []struct {
	Ctx context.Context
	Cfg system.UpdatesPut
} {
	var calls []struct {
		Ctx context.Context
		Cfg system.UpdatesPut
	}
	mock.lockUpdateUpdatesConfig.RLock()
	calls = mock.calls.UpdateUpdatesConfig
	mock.lockUpdateUpdatesConfig.RUnlock()
	return calls
}
