// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"io"
	"sync"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/google/uuid"
	"github.com/lxc/incus-os/incus-osd/api"
)

// Ensure that ClusterServiceMock does implement provisioning.ClusterService.
// If this is not the case, regenerate this file with mockery.
var _ provisioning.ClusterService = &ClusterServiceMock{}

// ClusterServiceMock is a mock implementation of provisioning.ClusterService.
//
//	func TestSomethingThatUsesClusterService(t *testing.T) {
//
//		// make and configure a mocked provisioning.ClusterService
//		mockedClusterService := &ClusterServiceMock{
//			AbortClusterUpdateFunc: func(ctx context.Context, name string) error {
//				panic("mock out the AbortClusterUpdate method")
//			},
//			AddApplicationFunc: func(ctx context.Context, clusterName string, applicationName string) error {
//				panic("mock out the AddApplication method")
//			},
//			AddServerSystemNetworkVLANTagsFunc: func(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error {
//				panic("mock out the AddServerSystemNetworkVLANTags method")
//			},
//			AddServersFunc: func(ctx context.Context, name string, serverNames []string, skipPostJoinOperations bool) error {
//				panic("mock out the AddServers method")
//			},
//			AddStorageTargetISCSIFunc: func(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error {
//				panic("mock out the AddStorageTargetISCSI method")
//			},
//			AddStorageTargetMultipathFunc: func(ctx context.Context, clusterName string, target string) error {
//				panic("mock out the AddStorageTargetMultipath method")
//			},
//			AddStorageTargetNVMEFunc: func(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error {
//				panic("mock out the AddStorageTargetNVME method")
//			},
//			ClusterUpdateControlLoopFunc: func(ctx context.Context, clusterNameFilter *string) error {
//				panic("mock out the ClusterUpdateControlLoop method")
//			},
//			CreateFunc: func(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error) {
//				panic("mock out the Create method")
//			},
//			DeleteAndFactoryResetByNameFunc: func(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string) error {
//				panic("mock out the DeleteAndFactoryResetByName method")
//			},
//			DeleteByNameFunc: func(ctx context.Context, name string, force bool) error {
//				panic("mock out the DeleteByName method")
//			},
//			GetAllFunc: func(ctx context.Context) (provisioning.Clusters, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNames method")
//			},
//			GetAllNamesWithFilterFunc: func(ctx context.Context, filter provisioning.ClusterFilter) ([]string, error) {
//				panic("mock out the GetAllNamesWithFilter method")
//			},
//			GetAllWithFilterFunc: func(ctx context.Context, filter provisioning.ClusterFilter) (provisioning.Clusters, error) {
//				panic("mock out the GetAllWithFilter method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*provisioning.Cluster, error) {
//				panic("mock out the GetByName method")
//			},
//			GetClusterArtifactAllFunc: func(ctx context.Context, clusterName string) (provisioning.ClusterArtifacts, error) {
//				panic("mock out the GetClusterArtifactAll method")
//			},
//			GetClusterArtifactAllNamesFunc: func(ctx context.Context, clusterName string) ([]string, error) {
//				panic("mock out the GetClusterArtifactAllNames method")
//			},
//			GetClusterArtifactArchiveByNameFunc: func(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (io.ReadCloser, int, error) {
//				panic("mock out the GetClusterArtifactArchiveByName method")
//			},
//			GetClusterArtifactByNameFunc: func(ctx context.Context, clusterName string, artifactName string) (*provisioning.ClusterArtifact, error) {
//				panic("mock out the GetClusterArtifactByName method")
//			},
//			GetClusterArtifactFileByNameFunc: func(ctx context.Context, clusterName string, artifactName string, filename string) (*provisioning.ClusterArtifactFile, error) {
//				panic("mock out the GetClusterArtifactFileByName method")
//			},
//			GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
//				panic("mock out the GetEndpoint method")
//			},
//			IsInstanceLifecycleOperationPermittedFunc: func(ctx context.Context, name string) bool {
//				panic("mock out the IsInstanceLifecycleOperationPermitted method")
//			},
//			LaunchClusterUpdateFunc: func(ctx context.Context, name string, reboot bool) error {
//				panic("mock out the LaunchClusterUpdate method")
//			},
//			RemoveServerFunc: func(ctx context.Context, name string, removedServerNames []string) error {
//				panic("mock out the RemoveServer method")
//			},
//			RemoveServerSystemNetworkVLANTagsFunc: func(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error {
//				panic("mock out the RemoveServerSystemNetworkVLANTags method")
//			},
//			RemoveStorageTargetISCSIFunc: func(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error {
//				panic("mock out the RemoveStorageTargetISCSI method")
//			},
//			RemoveStorageTargetMultipathFunc: func(ctx context.Context, clusterName string, target string) error {
//				panic("mock out the RemoveStorageTargetMultipath method")
//			},
//			RemoveStorageTargetNVMEFunc: func(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error {
//				panic("mock out the RemoveStorageTargetNVME method")
//			},
//			RenameFunc: func(ctx context.Context, oldName string, newName string) error {
//				panic("mock out the Rename method")
//			},
//			ResyncInventoryFunc: func(ctx context.Context) error {
//				panic("mock out the ResyncInventory method")
//			},
//			ResyncInventoryByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the ResyncInventoryByName method")
//			},
//			SetInventorySyncersFunc: func(inventorySyncers map[domain.ResourceType]provisioning.InventorySyncer)  {
//				panic("mock out the SetInventorySyncers method")
//			},
//			StartLifecycleEventsMonitorFunc: func(ctx context.Context) error {
//				panic("mock out the StartLifecycleEventsMonitor method")
//			},
//			UpdateFunc: func(ctx context.Context, cluster provisioning.Cluster, updateServers bool) error {
//				panic("mock out the Update method")
//			},
//			UpdateCertificateFunc: func(ctx context.Context, name string, certificatePEM string, keyPEM string) error {
//				panic("mock out the UpdateCertificate method")
//			},
//			UpdateSystemKernelFunc: func(ctx context.Context, clusterName string, kerneConfig provisioning.ServerSystemKernel) error {
//				panic("mock out the UpdateSystemKernel method")
//			},
//			UpdateSystemLoggingFunc: func(ctx context.Context, clusterName string, loggingConfig provisioning.ServerSystemLogging) error {
//				panic("mock out the UpdateSystemLogging method")
//			},
//		}
//
//		// use mockedClusterService in code that requires provisioning.ClusterService
//		// and then make assertions.
//
//	}
type ClusterServiceMock struct {
	// AbortClusterUpdateFunc mocks the AbortClusterUpdate method.
	AbortClusterUpdateFunc func(ctx context.Context, name string) error

	// AddApplicationFunc mocks the AddApplication method.
	AddApplicationFunc func(ctx context.Context, clusterName string, applicationName string) error

	// AddServerSystemNetworkVLANTagsFunc mocks the AddServerSystemNetworkVLANTags method.
	AddServerSystemNetworkVLANTagsFunc func(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error

	// AddServersFunc mocks the AddServers method.
	AddServersFunc func(ctx context.Context, name string, serverNames []string, skipPostJoinOperations bool) error

	// AddStorageTargetISCSIFunc mocks the AddStorageTargetISCSI method.
	AddStorageTargetISCSIFunc func(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error

	// AddStorageTargetMultipathFunc mocks the AddStorageTargetMultipath method.
	AddStorageTargetMultipathFunc func(ctx context.Context, clusterName string, target string) error

	// AddStorageTargetNVMEFunc mocks the AddStorageTargetNVME method.
	AddStorageTargetNVMEFunc func(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error

	// ClusterUpdateControlLoopFunc mocks the ClusterUpdateControlLoop method.
	ClusterUpdateControlLoopFunc func(ctx context.Context, clusterNameFilter *string) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error)

	// DeleteAndFactoryResetByNameFunc mocks the DeleteAndFactoryResetByName method.
	DeleteAndFactoryResetByNameFunc func(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string) error

	// DeleteByNameFunc mocks the DeleteByName method.
	DeleteByNameFunc func(ctx context.Context, name string, force bool) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (provisioning.Clusters, error)

	// GetAllNamesFunc mocks the GetAllNames method.
	GetAllNamesFunc func(ctx context.Context) ([]string, error)

	// GetAllNamesWithFilterFunc mocks the GetAllNamesWithFilter method.
	GetAllNamesWithFilterFunc func(ctx context.Context, filter provisioning.ClusterFilter) ([]string, error)

	// GetAllWithFilterFunc mocks the GetAllWithFilter method.
	GetAllWithFilterFunc func(ctx context.Context, filter provisioning.ClusterFilter) (provisioning.Clusters, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*provisioning.Cluster, error)

	// GetClusterArtifactAllFunc mocks the GetClusterArtifactAll method.
	GetClusterArtifactAllFunc func(ctx context.Context, clusterName string) (provisioning.ClusterArtifacts, error)

	// GetClusterArtifactAllNamesFunc mocks the GetClusterArtifactAllNames method.
	GetClusterArtifactAllNamesFunc func(ctx context.Context, clusterName string) ([]string, error)

	// GetClusterArtifactArchiveByNameFunc mocks the GetClusterArtifactArchiveByName method.
	GetClusterArtifactArchiveByNameFunc func(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (io.ReadCloser, int, error)

	// GetClusterArtifactByNameFunc mocks the GetClusterArtifactByName method.
	GetClusterArtifactByNameFunc func(ctx context.Context, clusterName string, artifactName string) (*provisioning.ClusterArtifact, error)

	// GetClusterArtifactFileByNameFunc mocks the GetClusterArtifactFileByName method.
	GetClusterArtifactFileByNameFunc func(ctx context.Context, clusterName string, artifactName string, filename string) (*provisioning.ClusterArtifactFile, error)

	// GetEndpointFunc mocks the GetEndpoint method.
	GetEndpointFunc func(ctx context.Context, name string) (provisioning.Endpoint, error)

	// IsInstanceLifecycleOperationPermittedFunc mocks the IsInstanceLifecycleOperationPermitted method.
	IsInstanceLifecycleOperationPermittedFunc func(ctx context.Context, name string) bool

	// LaunchClusterUpdateFunc mocks the LaunchClusterUpdate method.
	LaunchClusterUpdateFunc func(ctx context.Context, name string, reboot bool) error

	// RemoveServerFunc mocks the RemoveServer method.
	RemoveServerFunc func(ctx context.Context, name string, removedServerNames []string) error

	// RemoveServerSystemNetworkVLANTagsFunc mocks the RemoveServerSystemNetworkVLANTags method.
	RemoveServerSystemNetworkVLANTagsFunc func(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error

	// RemoveStorageTargetISCSIFunc mocks the RemoveStorageTargetISCSI method.
	RemoveStorageTargetISCSIFunc func(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error

	// RemoveStorageTargetMultipathFunc mocks the RemoveStorageTargetMultipath method.
	RemoveStorageTargetMultipathFunc func(ctx context.Context, clusterName string, target string) error

	// RemoveStorageTargetNVMEFunc mocks the RemoveStorageTargetNVME method.
	RemoveStorageTargetNVMEFunc func(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error

	// RenameFunc mocks the Rename method.
	RenameFunc func(ctx context.Context, oldName string, newName string) error

	// ResyncInventoryFunc mocks the ResyncInventory method.
	ResyncInventoryFunc func(ctx context.Context) error

	// ResyncInventoryByNameFunc mocks the ResyncInventoryByName method.
	ResyncInventoryByNameFunc func(ctx context.Context, name string) error

	// SetInventorySyncersFunc mocks the SetInventorySyncers method.
	SetInventorySyncersFunc func(inventorySyncers map[domain.ResourceType]provisioning.InventorySyncer)

	// StartLifecycleEventsMonitorFunc mocks the StartLifecycleEventsMonitor method.
	StartLifecycleEventsMonitorFunc func(ctx context.Context) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, cluster provisioning.Cluster, updateServers bool) error

	// UpdateCertificateFunc mocks the UpdateCertificate method.
	UpdateCertificateFunc func(ctx context.Context, name string, certificatePEM string, keyPEM string) error

	// UpdateSystemKernelFunc mocks the UpdateSystemKernel method.
	UpdateSystemKernelFunc func(ctx context.Context, clusterName string, kerneConfig provisioning.ServerSystemKernel) error

	// UpdateSystemLoggingFunc mocks the UpdateSystemLogging method.
	UpdateSystemLoggingFunc func(ctx context.Context, clusterName string, loggingConfig provisioning.ServerSystemLogging) error

	// calls tracks calls to the methods.
	calls struct {
		// AbortClusterUpdate holds details about calls to the AbortClusterUpdate method.
		AbortClusterUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// AddApplication holds details about calls to the AddApplication method.
		AddApplication []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// ApplicationName is the applicationName argument value.
			ApplicationName string
		}
		// AddServerSystemNetworkVLANTags holds details about calls to the AddServerSystemNetworkVLANTags method.
		AddServerSystemNetworkVLANTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// InterfaceName is the interfaceName argument value.
			InterfaceName string
			// VlanTags is the vlanTags argument value.
			VlanTags []int
		}
		// AddServers holds details about calls to the AddServers method.
		AddServers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ServerNames is the serverNames argument value.
			ServerNames []string
			// SkipPostJoinOperations is the skipPostJoinOperations argument value.
			SkipPostJoinOperations bool
		}
		// AddStorageTargetISCSI holds details about calls to the AddStorageTargetISCSI method.
		AddStorageTargetISCSI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target api.ServiceISCSITarget
		}
		// AddStorageTargetMultipath holds details about calls to the AddStorageTargetMultipath method.
		AddStorageTargetMultipath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target string
		}
		// AddStorageTargetNVME holds details about calls to the AddStorageTargetNVME method.
		AddStorageTargetNVME []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target api.ServiceNVMETarget
		}
		// ClusterUpdateControlLoop holds details about calls to the ClusterUpdateControlLoop method.
		ClusterUpdateControlLoop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterNameFilter is the clusterNameFilter argument value.
			ClusterNameFilter *string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster provisioning.Cluster
		}
		// DeleteAndFactoryResetByName holds details about calls to the DeleteAndFactoryResetByName method.
		DeleteAndFactoryResetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// TokenID is the tokenID argument value.
			TokenID *uuid.UUID
			// TokenSeedName is the tokenSeedName argument value.
			TokenSeedName *string
		}
		// DeleteByName holds details about calls to the DeleteByName method.
		DeleteByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Force is the force argument value.
			Force bool
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNames holds details about calls to the GetAllNames method.
		GetAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNamesWithFilter holds details about calls to the GetAllNamesWithFilter method.
		GetAllNamesWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter provisioning.ClusterFilter
		}
		// GetAllWithFilter holds details about calls to the GetAllWithFilter method.
		GetAllWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter provisioning.ClusterFilter
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetClusterArtifactAll holds details about calls to the GetClusterArtifactAll method.
		GetClusterArtifactAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
		}
		// GetClusterArtifactAllNames holds details about calls to the GetClusterArtifactAllNames method.
		GetClusterArtifactAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
		}
		// GetClusterArtifactArchiveByName holds details about calls to the GetClusterArtifactArchiveByName method.
		GetClusterArtifactArchiveByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// ArtifactName is the artifactName argument value.
			ArtifactName string
			// ArchiveType is the archiveType argument value.
			ArchiveType provisioning.ClusterArtifactArchiveType
		}
		// GetClusterArtifactByName holds details about calls to the GetClusterArtifactByName method.
		GetClusterArtifactByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// ArtifactName is the artifactName argument value.
			ArtifactName string
		}
		// GetClusterArtifactFileByName holds details about calls to the GetClusterArtifactFileByName method.
		GetClusterArtifactFileByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// ArtifactName is the artifactName argument value.
			ArtifactName string
			// Filename is the filename argument value.
			Filename string
		}
		// GetEndpoint holds details about calls to the GetEndpoint method.
		GetEndpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// IsInstanceLifecycleOperationPermitted holds details about calls to the IsInstanceLifecycleOperationPermitted method.
		IsInstanceLifecycleOperationPermitted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// LaunchClusterUpdate holds details about calls to the LaunchClusterUpdate method.
		LaunchClusterUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Reboot is the reboot argument value.
			Reboot bool
		}
		// RemoveServer holds details about calls to the RemoveServer method.
		RemoveServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// RemovedServerNames is the removedServerNames argument value.
			RemovedServerNames []string
		}
		// RemoveServerSystemNetworkVLANTags holds details about calls to the RemoveServerSystemNetworkVLANTags method.
		RemoveServerSystemNetworkVLANTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// InterfaceName is the interfaceName argument value.
			InterfaceName string
			// VlanTags is the vlanTags argument value.
			VlanTags []int
		}
		// RemoveStorageTargetISCSI holds details about calls to the RemoveStorageTargetISCSI method.
		RemoveStorageTargetISCSI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target api.ServiceISCSITarget
		}
		// RemoveStorageTargetMultipath holds details about calls to the RemoveStorageTargetMultipath method.
		RemoveStorageTargetMultipath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target string
		}
		// RemoveStorageTargetNVME holds details about calls to the RemoveStorageTargetNVME method.
		RemoveStorageTargetNVME []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Target is the target argument value.
			Target api.ServiceNVMETarget
		}
		// Rename holds details about calls to the Rename method.
		Rename []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldName is the oldName argument value.
			OldName string
			// NewName is the newName argument value.
			NewName string
		}
		// ResyncInventory holds details about calls to the ResyncInventory method.
		ResyncInventory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ResyncInventoryByName holds details about calls to the ResyncInventoryByName method.
		ResyncInventoryByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// SetInventorySyncers holds details about calls to the SetInventorySyncers method.
		SetInventorySyncers []struct {
			// InventorySyncers is the inventorySyncers argument value.
			InventorySyncers map[domain.ResourceType]provisioning.InventorySyncer
		}
		// StartLifecycleEventsMonitor holds details about calls to the StartLifecycleEventsMonitor method.
		StartLifecycleEventsMonitor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster provisioning.Cluster
			// UpdateServers is the updateServers argument value.
			UpdateServers bool
		}
		// UpdateCertificate holds details about calls to the UpdateCertificate method.
		UpdateCertificate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// CertificatePEM is the certificatePEM argument value.
			CertificatePEM string
			// KeyPEM is the keyPEM argument value.
			KeyPEM string
		}
		// UpdateSystemKernel holds details about calls to the UpdateSystemKernel method.
		UpdateSystemKernel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// KerneConfig is the kerneConfig argument value.
			KerneConfig provisioning.ServerSystemKernel
		}
		// UpdateSystemLogging holds details about calls to the UpdateSystemLogging method.
		UpdateSystemLogging []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterName is the clusterName argument value.
			ClusterName string
			// LoggingConfig is the loggingConfig argument value.
			LoggingConfig provisioning.ServerSystemLogging
		}
	}
	lockAbortClusterUpdate                    sync.RWMutex
	lockAddApplication                        sync.RWMutex
	lockAddServerSystemNetworkVLANTags        sync.RWMutex
	lockAddServers                            sync.RWMutex
	lockAddStorageTargetISCSI                 sync.RWMutex
	lockAddStorageTargetMultipath             sync.RWMutex
	lockAddStorageTargetNVME                  sync.RWMutex
	lockClusterUpdateControlLoop              sync.RWMutex
	lockCreate                                sync.RWMutex
	lockDeleteAndFactoryResetByName           sync.RWMutex
	lockDeleteByName                          sync.RWMutex
	lockGetAll                                sync.RWMutex
	lockGetAllNames                           sync.RWMutex
	lockGetAllNamesWithFilter                 sync.RWMutex
	lockGetAllWithFilter                      sync.RWMutex
	lockGetByName                             sync.RWMutex
	lockGetClusterArtifactAll                 sync.RWMutex
	lockGetClusterArtifactAllNames            sync.RWMutex
	lockGetClusterArtifactArchiveByName       sync.RWMutex
	lockGetClusterArtifactByName              sync.RWMutex
	lockGetClusterArtifactFileByName          sync.RWMutex
	lockGetEndpoint                           sync.RWMutex
	lockIsInstanceLifecycleOperationPermitted sync.RWMutex
	lockLaunchClusterUpdate                   sync.RWMutex
	lockRemoveServer                          sync.RWMutex
	lockRemoveServerSystemNetworkVLANTags     sync.RWMutex
	lockRemoveStorageTargetISCSI              sync.RWMutex
	lockRemoveStorageTargetMultipath          sync.RWMutex
	lockRemoveStorageTargetNVME               sync.RWMutex
	lockRename                                sync.RWMutex
	lockResyncInventory                       sync.RWMutex
	lockResyncInventoryByName                 sync.RWMutex
	lockSetInventorySyncers                   sync.RWMutex
	lockStartLifecycleEventsMonitor           sync.RWMutex
	lockUpdate                                sync.RWMutex
	lockUpdateCertificate                     sync.RWMutex
	lockUpdateSystemKernel                    sync.RWMutex
	lockUpdateSystemLogging                   sync.RWMutex
}

// AbortClusterUpdate calls AbortClusterUpdateFunc.
func (mock *ClusterServiceMock) AbortClusterUpdate(ctx context.Context, name string) error {
	if mock.AbortClusterUpdateFunc == nil {
		panic("ClusterServiceMock.AbortClusterUpdateFunc: method is nil but ClusterService.AbortClusterUpdate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockAbortClusterUpdate.Lock()
	mock.calls.AbortClusterUpdate = append(mock.calls.AbortClusterUpdate, callInfo)
	mock.lockAbortClusterUpdate.Unlock()
	return mock.AbortClusterUpdateFunc(ctx, name)
}

// AbortClusterUpdateCalls gets all the calls that were made to AbortClusterUpdate.
// Check the length with:
//
//	len(mockedClusterService.AbortClusterUpdateCalls())
func (mock *ClusterServiceMock) AbortClusterUpdateCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockAbortClusterUpdate.RLock()
	calls = mock.calls.AbortClusterUpdate
	mock.lockAbortClusterUpdate.RUnlock()
	return calls
}

// AddApplication calls AddApplicationFunc.
func (mock *ClusterServiceMock) AddApplication(ctx context.Context, clusterName string, applicationName string) error {
	if mock.AddApplicationFunc == nil {
		panic("ClusterServiceMock.AddApplicationFunc: method is nil but ClusterService.AddApplication was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		ClusterName     string
		ApplicationName string
	}{
		Ctx:             ctx,
		ClusterName:     clusterName,
		ApplicationName: applicationName,
	}
	mock.lockAddApplication.Lock()
	mock.calls.AddApplication = append(mock.calls.AddApplication, callInfo)
	mock.lockAddApplication.Unlock()
	return mock.AddApplicationFunc(ctx, clusterName, applicationName)
}

// AddApplicationCalls gets all the calls that were made to AddApplication.
// Check the length with:
//
//	len(mockedClusterService.AddApplicationCalls())
func (mock *ClusterServiceMock) AddApplicationCalls() []struct {
	Ctx             context.Context
	ClusterName     string
	ApplicationName string
} {
	var calls []struct {
		Ctx             context.Context
		ClusterName     string
		ApplicationName string
	}
	mock.lockAddApplication.RLock()
	calls = mock.calls.AddApplication
	mock.lockAddApplication.RUnlock()
	return calls
}

// AddServerSystemNetworkVLANTags calls AddServerSystemNetworkVLANTagsFunc.
func (mock *ClusterServiceMock) AddServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error {
	if mock.AddServerSystemNetworkVLANTagsFunc == nil {
		panic("ClusterServiceMock.AddServerSystemNetworkVLANTagsFunc: method is nil but ClusterService.AddServerSystemNetworkVLANTags was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ClusterName   string
		InterfaceName string
		VlanTags      []int
	}{
		Ctx:           ctx,
		ClusterName:   clusterName,
		InterfaceName: interfaceName,
		VlanTags:      vlanTags,
	}
	mock.lockAddServerSystemNetworkVLANTags.Lock()
	mock.calls.AddServerSystemNetworkVLANTags = append(mock.calls.AddServerSystemNetworkVLANTags, callInfo)
	mock.lockAddServerSystemNetworkVLANTags.Unlock()
	return mock.AddServerSystemNetworkVLANTagsFunc(ctx, clusterName, interfaceName, vlanTags)
}

// AddServerSystemNetworkVLANTagsCalls gets all the calls that were made to AddServerSystemNetworkVLANTags.
// Check the length with:
//
//	len(mockedClusterService.AddServerSystemNetworkVLANTagsCalls())
func (mock *ClusterServiceMock) AddServerSystemNetworkVLANTagsCalls() []struct {
	Ctx           context.Context
	ClusterName   string
	InterfaceName string
	VlanTags      []int
} {
	var calls []struct {
		Ctx           context.Context
		ClusterName   string
		InterfaceName string
		VlanTags      []int
	}
	mock.lockAddServerSystemNetworkVLANTags.RLock()
	calls = mock.calls.AddServerSystemNetworkVLANTags
	mock.lockAddServerSystemNetworkVLANTags.RUnlock()
	return calls
}

// AddServers calls AddServersFunc.
func (mock *ClusterServiceMock) AddServers(ctx context.Context, name string, serverNames []string, skipPostJoinOperations bool) error {
	if mock.AddServersFunc == nil {
		panic("ClusterServiceMock.AddServersFunc: method is nil but ClusterService.AddServers was just called")
	}
	callInfo := struct {
		Ctx                    context.Context
		Name                   string
		ServerNames            []string
		SkipPostJoinOperations bool
	}{
		Ctx:                    ctx,
		Name:                   name,
		ServerNames:            serverNames,
		SkipPostJoinOperations: skipPostJoinOperations,
	}
	mock.lockAddServers.Lock()
	mock.calls.AddServers = append(mock.calls.AddServers, callInfo)
	mock.lockAddServers.Unlock()
	return mock.AddServersFunc(ctx, name, serverNames, skipPostJoinOperations)
}

// AddServersCalls gets all the calls that were made to AddServers.
// Check the length with:
//
//	len(mockedClusterService.AddServersCalls())
func (mock *ClusterServiceMock) AddServersCalls() []struct {
	Ctx                    context.Context
	Name                   string
	ServerNames            []string
	SkipPostJoinOperations bool
} {
	var calls []struct {
		Ctx                    context.Context
		Name                   string
		ServerNames            []string
		SkipPostJoinOperations bool
	}
	mock.lockAddServers.RLock()
	calls = mock.calls.AddServers
	mock.lockAddServers.RUnlock()
	return calls
}

// AddStorageTargetISCSI calls AddStorageTargetISCSIFunc.
func (mock *ClusterServiceMock) AddStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error {
	if mock.AddStorageTargetISCSIFunc == nil {
		panic("ClusterServiceMock.AddStorageTargetISCSIFunc: method is nil but ClusterService.AddStorageTargetISCSI was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceISCSITarget
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockAddStorageTargetISCSI.Lock()
	mock.calls.AddStorageTargetISCSI = append(mock.calls.AddStorageTargetISCSI, callInfo)
	mock.lockAddStorageTargetISCSI.Unlock()
	return mock.AddStorageTargetISCSIFunc(ctx, clusterName, target)
}

// AddStorageTargetISCSICalls gets all the calls that were made to AddStorageTargetISCSI.
// Check the length with:
//
//	len(mockedClusterService.AddStorageTargetISCSICalls())
func (mock *ClusterServiceMock) AddStorageTargetISCSICalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      api.ServiceISCSITarget
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceISCSITarget
	}
	mock.lockAddStorageTargetISCSI.RLock()
	calls = mock.calls.AddStorageTargetISCSI
	mock.lockAddStorageTargetISCSI.RUnlock()
	return calls
}

// AddStorageTargetMultipath calls AddStorageTargetMultipathFunc.
func (mock *ClusterServiceMock) AddStorageTargetMultipath(ctx context.Context, clusterName string, target string) error {
	if mock.AddStorageTargetMultipathFunc == nil {
		panic("ClusterServiceMock.AddStorageTargetMultipathFunc: method is nil but ClusterService.AddStorageTargetMultipath was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      string
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockAddStorageTargetMultipath.Lock()
	mock.calls.AddStorageTargetMultipath = append(mock.calls.AddStorageTargetMultipath, callInfo)
	mock.lockAddStorageTargetMultipath.Unlock()
	return mock.AddStorageTargetMultipathFunc(ctx, clusterName, target)
}

// AddStorageTargetMultipathCalls gets all the calls that were made to AddStorageTargetMultipath.
// Check the length with:
//
//	len(mockedClusterService.AddStorageTargetMultipathCalls())
func (mock *ClusterServiceMock) AddStorageTargetMultipathCalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      string
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      string
	}
	mock.lockAddStorageTargetMultipath.RLock()
	calls = mock.calls.AddStorageTargetMultipath
	mock.lockAddStorageTargetMultipath.RUnlock()
	return calls
}

// AddStorageTargetNVME calls AddStorageTargetNVMEFunc.
func (mock *ClusterServiceMock) AddStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error {
	if mock.AddStorageTargetNVMEFunc == nil {
		panic("ClusterServiceMock.AddStorageTargetNVMEFunc: method is nil but ClusterService.AddStorageTargetNVME was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceNVMETarget
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockAddStorageTargetNVME.Lock()
	mock.calls.AddStorageTargetNVME = append(mock.calls.AddStorageTargetNVME, callInfo)
	mock.lockAddStorageTargetNVME.Unlock()
	return mock.AddStorageTargetNVMEFunc(ctx, clusterName, target)
}

// AddStorageTargetNVMECalls gets all the calls that were made to AddStorageTargetNVME.
// Check the length with:
//
//	len(mockedClusterService.AddStorageTargetNVMECalls())
func (mock *ClusterServiceMock) AddStorageTargetNVMECalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      api.ServiceNVMETarget
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceNVMETarget
	}
	mock.lockAddStorageTargetNVME.RLock()
	calls = mock.calls.AddStorageTargetNVME
	mock.lockAddStorageTargetNVME.RUnlock()
	return calls
}

// ClusterUpdateControlLoop calls ClusterUpdateControlLoopFunc.
func (mock *ClusterServiceMock) ClusterUpdateControlLoop(ctx context.Context, clusterNameFilter *string) error {
	if mock.ClusterUpdateControlLoopFunc == nil {
		panic("ClusterServiceMock.ClusterUpdateControlLoopFunc: method is nil but ClusterService.ClusterUpdateControlLoop was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		ClusterNameFilter *string
	}{
		Ctx:               ctx,
		ClusterNameFilter: clusterNameFilter,
	}
	mock.lockClusterUpdateControlLoop.Lock()
	mock.calls.ClusterUpdateControlLoop = append(mock.calls.ClusterUpdateControlLoop, callInfo)
	mock.lockClusterUpdateControlLoop.Unlock()
	return mock.ClusterUpdateControlLoopFunc(ctx, clusterNameFilter)
}

// ClusterUpdateControlLoopCalls gets all the calls that were made to ClusterUpdateControlLoop.
// Check the length with:
//
//	len(mockedClusterService.ClusterUpdateControlLoopCalls())
func (mock *ClusterServiceMock) ClusterUpdateControlLoopCalls() []struct {
	Ctx               context.Context
	ClusterNameFilter *string
} {
	var calls []struct {
		Ctx               context.Context
		ClusterNameFilter *string
	}
	mock.lockClusterUpdateControlLoop.RLock()
	calls = mock.calls.ClusterUpdateControlLoop
	mock.lockClusterUpdateControlLoop.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ClusterServiceMock) Create(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error) {
	if mock.CreateFunc == nil {
		panic("ClusterServiceMock.CreateFunc: method is nil but ClusterService.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Cluster provisioning.Cluster
	}{
		Ctx:     ctx,
		Cluster: cluster,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, cluster)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedClusterService.CreateCalls())
func (mock *ClusterServiceMock) CreateCalls() []struct {
	Ctx     context.Context
	Cluster provisioning.Cluster
} {
	var calls []struct {
		Ctx     context.Context
		Cluster provisioning.Cluster
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteAndFactoryResetByName calls DeleteAndFactoryResetByNameFunc.
func (mock *ClusterServiceMock) DeleteAndFactoryResetByName(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string) error {
	if mock.DeleteAndFactoryResetByNameFunc == nil {
		panic("ClusterServiceMock.DeleteAndFactoryResetByNameFunc: method is nil but ClusterService.DeleteAndFactoryResetByName was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Name          string
		TokenID       *uuid.UUID
		TokenSeedName *string
	}{
		Ctx:           ctx,
		Name:          name,
		TokenID:       tokenID,
		TokenSeedName: tokenSeedName,
	}
	mock.lockDeleteAndFactoryResetByName.Lock()
	mock.calls.DeleteAndFactoryResetByName = append(mock.calls.DeleteAndFactoryResetByName, callInfo)
	mock.lockDeleteAndFactoryResetByName.Unlock()
	return mock.DeleteAndFactoryResetByNameFunc(ctx, name, tokenID, tokenSeedName)
}

// DeleteAndFactoryResetByNameCalls gets all the calls that were made to DeleteAndFactoryResetByName.
// Check the length with:
//
//	len(mockedClusterService.DeleteAndFactoryResetByNameCalls())
func (mock *ClusterServiceMock) DeleteAndFactoryResetByNameCalls() []struct {
	Ctx           context.Context
	Name          string
	TokenID       *uuid.UUID
	TokenSeedName *string
} {
	var calls []struct {
		Ctx           context.Context
		Name          string
		TokenID       *uuid.UUID
		TokenSeedName *string
	}
	mock.lockDeleteAndFactoryResetByName.RLock()
	calls = mock.calls.DeleteAndFactoryResetByName
	mock.lockDeleteAndFactoryResetByName.RUnlock()
	return calls
}

// DeleteByName calls DeleteByNameFunc.
func (mock *ClusterServiceMock) DeleteByName(ctx context.Context, name string, force bool) error {
	if mock.DeleteByNameFunc == nil {
		panic("ClusterServiceMock.DeleteByNameFunc: method is nil but ClusterService.DeleteByName was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Force bool
	}{
		Ctx:   ctx,
		Name:  name,
		Force: force,
	}
	mock.lockDeleteByName.Lock()
	mock.calls.DeleteByName = append(mock.calls.DeleteByName, callInfo)
	mock.lockDeleteByName.Unlock()
	return mock.DeleteByNameFunc(ctx, name, force)
}

// DeleteByNameCalls gets all the calls that were made to DeleteByName.
// Check the length with:
//
//	len(mockedClusterService.DeleteByNameCalls())
func (mock *ClusterServiceMock) DeleteByNameCalls() []struct {
	Ctx   context.Context
	Name  string
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Force bool
	}
	mock.lockDeleteByName.RLock()
	calls = mock.calls.DeleteByName
	mock.lockDeleteByName.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *ClusterServiceMock) GetAll(ctx context.Context) (provisioning.Clusters, error) {
	if mock.GetAllFunc == nil {
		panic("ClusterServiceMock.GetAllFunc: method is nil but ClusterService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedClusterService.GetAllCalls())
func (mock *ClusterServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllNames calls GetAllNamesFunc.
func (mock *ClusterServiceMock) GetAllNames(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesFunc == nil {
		panic("ClusterServiceMock.GetAllNamesFunc: method is nil but ClusterService.GetAllNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNames.Lock()
	mock.calls.GetAllNames = append(mock.calls.GetAllNames, callInfo)
	mock.lockGetAllNames.Unlock()
	return mock.GetAllNamesFunc(ctx)
}

// GetAllNamesCalls gets all the calls that were made to GetAllNames.
// Check the length with:
//
//	len(mockedClusterService.GetAllNamesCalls())
func (mock *ClusterServiceMock) GetAllNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNames.RLock()
	calls = mock.calls.GetAllNames
	mock.lockGetAllNames.RUnlock()
	return calls
}

// GetAllNamesWithFilter calls GetAllNamesWithFilterFunc.
func (mock *ClusterServiceMock) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ClusterFilter) ([]string, error) {
	if mock.GetAllNamesWithFilterFunc == nil {
		panic("ClusterServiceMock.GetAllNamesWithFilterFunc: method is nil but ClusterService.GetAllNamesWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter provisioning.ClusterFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllNamesWithFilter.Lock()
	mock.calls.GetAllNamesWithFilter = append(mock.calls.GetAllNamesWithFilter, callInfo)
	mock.lockGetAllNamesWithFilter.Unlock()
	return mock.GetAllNamesWithFilterFunc(ctx, filter)
}

// GetAllNamesWithFilterCalls gets all the calls that were made to GetAllNamesWithFilter.
// Check the length with:
//
//	len(mockedClusterService.GetAllNamesWithFilterCalls())
func (mock *ClusterServiceMock) GetAllNamesWithFilterCalls() []struct {
	Ctx    context.Context
	Filter provisioning.ClusterFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter provisioning.ClusterFilter
	}
	mock.lockGetAllNamesWithFilter.RLock()
	calls = mock.calls.GetAllNamesWithFilter
	mock.lockGetAllNamesWithFilter.RUnlock()
	return calls
}

// GetAllWithFilter calls GetAllWithFilterFunc.
func (mock *ClusterServiceMock) GetAllWithFilter(ctx context.Context, filter provisioning.ClusterFilter) (provisioning.Clusters, error) {
	if mock.GetAllWithFilterFunc == nil {
		panic("ClusterServiceMock.GetAllWithFilterFunc: method is nil but ClusterService.GetAllWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter provisioning.ClusterFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllWithFilter.Lock()
	mock.calls.GetAllWithFilter = append(mock.calls.GetAllWithFilter, callInfo)
	mock.lockGetAllWithFilter.Unlock()
	return mock.GetAllWithFilterFunc(ctx, filter)
}

// GetAllWithFilterCalls gets all the calls that were made to GetAllWithFilter.
// Check the length with:
//
//	len(mockedClusterService.GetAllWithFilterCalls())
func (mock *ClusterServiceMock) GetAllWithFilterCalls() []struct {
	Ctx    context.Context
	Filter provisioning.ClusterFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter provisioning.ClusterFilter
	}
	mock.lockGetAllWithFilter.RLock()
	calls = mock.calls.GetAllWithFilter
	mock.lockGetAllWithFilter.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *ClusterServiceMock) GetByName(ctx context.Context, name string) (*provisioning.Cluster, error) {
	if mock.GetByNameFunc == nil {
		panic("ClusterServiceMock.GetByNameFunc: method is nil but ClusterService.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedClusterService.GetByNameCalls())
func (mock *ClusterServiceMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// GetClusterArtifactAll calls GetClusterArtifactAllFunc.
func (mock *ClusterServiceMock) GetClusterArtifactAll(ctx context.Context, clusterName string) (provisioning.ClusterArtifacts, error) {
	if mock.GetClusterArtifactAllFunc == nil {
		panic("ClusterServiceMock.GetClusterArtifactAllFunc: method is nil but ClusterService.GetClusterArtifactAll was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
	}
	mock.lockGetClusterArtifactAll.Lock()
	mock.calls.GetClusterArtifactAll = append(mock.calls.GetClusterArtifactAll, callInfo)
	mock.lockGetClusterArtifactAll.Unlock()
	return mock.GetClusterArtifactAllFunc(ctx, clusterName)
}

// GetClusterArtifactAllCalls gets all the calls that were made to GetClusterArtifactAll.
// Check the length with:
//
//	len(mockedClusterService.GetClusterArtifactAllCalls())
func (mock *ClusterServiceMock) GetClusterArtifactAllCalls() []struct {
	Ctx         context.Context
	ClusterName string
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
	}
	mock.lockGetClusterArtifactAll.RLock()
	calls = mock.calls.GetClusterArtifactAll
	mock.lockGetClusterArtifactAll.RUnlock()
	return calls
}

// GetClusterArtifactAllNames calls GetClusterArtifactAllNamesFunc.
func (mock *ClusterServiceMock) GetClusterArtifactAllNames(ctx context.Context, clusterName string) ([]string, error) {
	if mock.GetClusterArtifactAllNamesFunc == nil {
		panic("ClusterServiceMock.GetClusterArtifactAllNamesFunc: method is nil but ClusterService.GetClusterArtifactAllNames was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
	}
	mock.lockGetClusterArtifactAllNames.Lock()
	mock.calls.GetClusterArtifactAllNames = append(mock.calls.GetClusterArtifactAllNames, callInfo)
	mock.lockGetClusterArtifactAllNames.Unlock()
	return mock.GetClusterArtifactAllNamesFunc(ctx, clusterName)
}

// GetClusterArtifactAllNamesCalls gets all the calls that were made to GetClusterArtifactAllNames.
// Check the length with:
//
//	len(mockedClusterService.GetClusterArtifactAllNamesCalls())
func (mock *ClusterServiceMock) GetClusterArtifactAllNamesCalls() []struct {
	Ctx         context.Context
	ClusterName string
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
	}
	mock.lockGetClusterArtifactAllNames.RLock()
	calls = mock.calls.GetClusterArtifactAllNames
	mock.lockGetClusterArtifactAllNames.RUnlock()
	return calls
}

// GetClusterArtifactArchiveByName calls GetClusterArtifactArchiveByNameFunc.
func (mock *ClusterServiceMock) GetClusterArtifactArchiveByName(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (io.ReadCloser, int, error) {
	if mock.GetClusterArtifactArchiveByNameFunc == nil {
		panic("ClusterServiceMock.GetClusterArtifactArchiveByNameFunc: method is nil but ClusterService.GetClusterArtifactArchiveByName was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
		ArchiveType  provisioning.ClusterArtifactArchiveType
	}{
		Ctx:          ctx,
		ClusterName:  clusterName,
		ArtifactName: artifactName,
		ArchiveType:  archiveType,
	}
	mock.lockGetClusterArtifactArchiveByName.Lock()
	mock.calls.GetClusterArtifactArchiveByName = append(mock.calls.GetClusterArtifactArchiveByName, callInfo)
	mock.lockGetClusterArtifactArchiveByName.Unlock()
	return mock.GetClusterArtifactArchiveByNameFunc(ctx, clusterName, artifactName, archiveType)
}

// GetClusterArtifactArchiveByNameCalls gets all the calls that were made to GetClusterArtifactArchiveByName.
// Check the length with:
//
//	len(mockedClusterService.GetClusterArtifactArchiveByNameCalls())
func (mock *ClusterServiceMock) GetClusterArtifactArchiveByNameCalls() []struct {
	Ctx          context.Context
	ClusterName  string
	ArtifactName string
	ArchiveType  provisioning.ClusterArtifactArchiveType
} {
	var calls []struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
		ArchiveType  provisioning.ClusterArtifactArchiveType
	}
	mock.lockGetClusterArtifactArchiveByName.RLock()
	calls = mock.calls.GetClusterArtifactArchiveByName
	mock.lockGetClusterArtifactArchiveByName.RUnlock()
	return calls
}

// GetClusterArtifactByName calls GetClusterArtifactByNameFunc.
func (mock *ClusterServiceMock) GetClusterArtifactByName(ctx context.Context, clusterName string, artifactName string) (*provisioning.ClusterArtifact, error) {
	if mock.GetClusterArtifactByNameFunc == nil {
		panic("ClusterServiceMock.GetClusterArtifactByNameFunc: method is nil but ClusterService.GetClusterArtifactByName was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
	}{
		Ctx:          ctx,
		ClusterName:  clusterName,
		ArtifactName: artifactName,
	}
	mock.lockGetClusterArtifactByName.Lock()
	mock.calls.GetClusterArtifactByName = append(mock.calls.GetClusterArtifactByName, callInfo)
	mock.lockGetClusterArtifactByName.Unlock()
	return mock.GetClusterArtifactByNameFunc(ctx, clusterName, artifactName)
}

// GetClusterArtifactByNameCalls gets all the calls that were made to GetClusterArtifactByName.
// Check the length with:
//
//	len(mockedClusterService.GetClusterArtifactByNameCalls())
func (mock *ClusterServiceMock) GetClusterArtifactByNameCalls() []struct {
	Ctx          context.Context
	ClusterName  string
	ArtifactName string
} {
	var calls []struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
	}
	mock.lockGetClusterArtifactByName.RLock()
	calls = mock.calls.GetClusterArtifactByName
	mock.lockGetClusterArtifactByName.RUnlock()
	return calls
}

// GetClusterArtifactFileByName calls GetClusterArtifactFileByNameFunc.
func (mock *ClusterServiceMock) GetClusterArtifactFileByName(ctx context.Context, clusterName string, artifactName string, filename string) (*provisioning.ClusterArtifactFile, error) {
	if mock.GetClusterArtifactFileByNameFunc == nil {
		panic("ClusterServiceMock.GetClusterArtifactFileByNameFunc: method is nil but ClusterService.GetClusterArtifactFileByName was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
		Filename     string
	}{
		Ctx:          ctx,
		ClusterName:  clusterName,
		ArtifactName: artifactName,
		Filename:     filename,
	}
	mock.lockGetClusterArtifactFileByName.Lock()
	mock.calls.GetClusterArtifactFileByName = append(mock.calls.GetClusterArtifactFileByName, callInfo)
	mock.lockGetClusterArtifactFileByName.Unlock()
	return mock.GetClusterArtifactFileByNameFunc(ctx, clusterName, artifactName, filename)
}

// GetClusterArtifactFileByNameCalls gets all the calls that were made to GetClusterArtifactFileByName.
// Check the length with:
//
//	len(mockedClusterService.GetClusterArtifactFileByNameCalls())
func (mock *ClusterServiceMock) GetClusterArtifactFileByNameCalls() []struct {
	Ctx          context.Context
	ClusterName  string
	ArtifactName string
	Filename     string
} {
	var calls []struct {
		Ctx          context.Context
		ClusterName  string
		ArtifactName string
		Filename     string
	}
	mock.lockGetClusterArtifactFileByName.RLock()
	calls = mock.calls.GetClusterArtifactFileByName
	mock.lockGetClusterArtifactFileByName.RUnlock()
	return calls
}

// GetEndpoint calls GetEndpointFunc.
func (mock *ClusterServiceMock) GetEndpoint(ctx context.Context, name string) (provisioning.Endpoint, error) {
	if mock.GetEndpointFunc == nil {
		panic("ClusterServiceMock.GetEndpointFunc: method is nil but ClusterService.GetEndpoint was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetEndpoint.Lock()
	mock.calls.GetEndpoint = append(mock.calls.GetEndpoint, callInfo)
	mock.lockGetEndpoint.Unlock()
	return mock.GetEndpointFunc(ctx, name)
}

// GetEndpointCalls gets all the calls that were made to GetEndpoint.
// Check the length with:
//
//	len(mockedClusterService.GetEndpointCalls())
func (mock *ClusterServiceMock) GetEndpointCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetEndpoint.RLock()
	calls = mock.calls.GetEndpoint
	mock.lockGetEndpoint.RUnlock()
	return calls
}

// IsInstanceLifecycleOperationPermitted calls IsInstanceLifecycleOperationPermittedFunc.
func (mock *ClusterServiceMock) IsInstanceLifecycleOperationPermitted(ctx context.Context, name string) bool {
	if mock.IsInstanceLifecycleOperationPermittedFunc == nil {
		panic("ClusterServiceMock.IsInstanceLifecycleOperationPermittedFunc: method is nil but ClusterService.IsInstanceLifecycleOperationPermitted was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockIsInstanceLifecycleOperationPermitted.Lock()
	mock.calls.IsInstanceLifecycleOperationPermitted = append(mock.calls.IsInstanceLifecycleOperationPermitted, callInfo)
	mock.lockIsInstanceLifecycleOperationPermitted.Unlock()
	return mock.IsInstanceLifecycleOperationPermittedFunc(ctx, name)
}

// IsInstanceLifecycleOperationPermittedCalls gets all the calls that were made to IsInstanceLifecycleOperationPermitted.
// Check the length with:
//
//	len(mockedClusterService.IsInstanceLifecycleOperationPermittedCalls())
func (mock *ClusterServiceMock) IsInstanceLifecycleOperationPermittedCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockIsInstanceLifecycleOperationPermitted.RLock()
	calls = mock.calls.IsInstanceLifecycleOperationPermitted
	mock.lockIsInstanceLifecycleOperationPermitted.RUnlock()
	return calls
}

// LaunchClusterUpdate calls LaunchClusterUpdateFunc.
func (mock *ClusterServiceMock) LaunchClusterUpdate(ctx context.Context, name string, reboot bool) error {
	if mock.LaunchClusterUpdateFunc == nil {
		panic("ClusterServiceMock.LaunchClusterUpdateFunc: method is nil but ClusterService.LaunchClusterUpdate was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Name   string
		Reboot bool
	}{
		Ctx:    ctx,
		Name:   name,
		Reboot: reboot,
	}
	mock.lockLaunchClusterUpdate.Lock()
	mock.calls.LaunchClusterUpdate = append(mock.calls.LaunchClusterUpdate, callInfo)
	mock.lockLaunchClusterUpdate.Unlock()
	return mock.LaunchClusterUpdateFunc(ctx, name, reboot)
}

// LaunchClusterUpdateCalls gets all the calls that were made to LaunchClusterUpdate.
// Check the length with:
//
//	len(mockedClusterService.LaunchClusterUpdateCalls())
func (mock *ClusterServiceMock) LaunchClusterUpdateCalls() []struct {
	Ctx    context.Context
	Name   string
	Reboot bool
} {
	var calls []struct {
		Ctx    context.Context
		Name   string
		Reboot bool
	}
	mock.lockLaunchClusterUpdate.RLock()
	calls = mock.calls.LaunchClusterUpdate
	mock.lockLaunchClusterUpdate.RUnlock()
	return calls
}

// RemoveServer calls RemoveServerFunc.
func (mock *ClusterServiceMock) RemoveServer(ctx context.Context, name string, removedServerNames []string) error {
	if mock.RemoveServerFunc == nil {
		panic("ClusterServiceMock.RemoveServerFunc: method is nil but ClusterService.RemoveServer was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		Name               string
		RemovedServerNames []string
	}{
		Ctx:                ctx,
		Name:               name,
		RemovedServerNames: removedServerNames,
	}
	mock.lockRemoveServer.Lock()
	mock.calls.RemoveServer = append(mock.calls.RemoveServer, callInfo)
	mock.lockRemoveServer.Unlock()
	return mock.RemoveServerFunc(ctx, name, removedServerNames)
}

// RemoveServerCalls gets all the calls that were made to RemoveServer.
// Check the length with:
//
//	len(mockedClusterService.RemoveServerCalls())
func (mock *ClusterServiceMock) RemoveServerCalls() []struct {
	Ctx                context.Context
	Name               string
	RemovedServerNames []string
} {
	var calls []struct {
		Ctx                context.Context
		Name               string
		RemovedServerNames []string
	}
	mock.lockRemoveServer.RLock()
	calls = mock.calls.RemoveServer
	mock.lockRemoveServer.RUnlock()
	return calls
}

// RemoveServerSystemNetworkVLANTags calls RemoveServerSystemNetworkVLANTagsFunc.
func (mock *ClusterServiceMock) RemoveServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) error {
	if mock.RemoveServerSystemNetworkVLANTagsFunc == nil {
		panic("ClusterServiceMock.RemoveServerSystemNetworkVLANTagsFunc: method is nil but ClusterService.RemoveServerSystemNetworkVLANTags was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ClusterName   string
		InterfaceName string
		VlanTags      []int
	}{
		Ctx:           ctx,
		ClusterName:   clusterName,
		InterfaceName: interfaceName,
		VlanTags:      vlanTags,
	}
	mock.lockRemoveServerSystemNetworkVLANTags.Lock()
	mock.calls.RemoveServerSystemNetworkVLANTags = append(mock.calls.RemoveServerSystemNetworkVLANTags, callInfo)
	mock.lockRemoveServerSystemNetworkVLANTags.Unlock()
	return mock.RemoveServerSystemNetworkVLANTagsFunc(ctx, clusterName, interfaceName, vlanTags)
}

// RemoveServerSystemNetworkVLANTagsCalls gets all the calls that were made to RemoveServerSystemNetworkVLANTags.
// Check the length with:
//
//	len(mockedClusterService.RemoveServerSystemNetworkVLANTagsCalls())
func (mock *ClusterServiceMock) RemoveServerSystemNetworkVLANTagsCalls() []struct {
	Ctx           context.Context
	ClusterName   string
	InterfaceName string
	VlanTags      []int
} {
	var calls []struct {
		Ctx           context.Context
		ClusterName   string
		InterfaceName string
		VlanTags      []int
	}
	mock.lockRemoveServerSystemNetworkVLANTags.RLock()
	calls = mock.calls.RemoveServerSystemNetworkVLANTags
	mock.lockRemoveServerSystemNetworkVLANTags.RUnlock()
	return calls
}

// RemoveStorageTargetISCSI calls RemoveStorageTargetISCSIFunc.
func (mock *ClusterServiceMock) RemoveStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) error {
	if mock.RemoveStorageTargetISCSIFunc == nil {
		panic("ClusterServiceMock.RemoveStorageTargetISCSIFunc: method is nil but ClusterService.RemoveStorageTargetISCSI was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceISCSITarget
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockRemoveStorageTargetISCSI.Lock()
	mock.calls.RemoveStorageTargetISCSI = append(mock.calls.RemoveStorageTargetISCSI, callInfo)
	mock.lockRemoveStorageTargetISCSI.Unlock()
	return mock.RemoveStorageTargetISCSIFunc(ctx, clusterName, target)
}

// RemoveStorageTargetISCSICalls gets all the calls that were made to RemoveStorageTargetISCSI.
// Check the length with:
//
//	len(mockedClusterService.RemoveStorageTargetISCSICalls())
func (mock *ClusterServiceMock) RemoveStorageTargetISCSICalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      api.ServiceISCSITarget
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceISCSITarget
	}
	mock.lockRemoveStorageTargetISCSI.RLock()
	calls = mock.calls.RemoveStorageTargetISCSI
	mock.lockRemoveStorageTargetISCSI.RUnlock()
	return calls
}

// RemoveStorageTargetMultipath calls RemoveStorageTargetMultipathFunc.
func (mock *ClusterServiceMock) RemoveStorageTargetMultipath(ctx context.Context, clusterName string, target string) error {
	if mock.RemoveStorageTargetMultipathFunc == nil {
		panic("ClusterServiceMock.RemoveStorageTargetMultipathFunc: method is nil but ClusterService.RemoveStorageTargetMultipath was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      string
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockRemoveStorageTargetMultipath.Lock()
	mock.calls.RemoveStorageTargetMultipath = append(mock.calls.RemoveStorageTargetMultipath, callInfo)
	mock.lockRemoveStorageTargetMultipath.Unlock()
	return mock.RemoveStorageTargetMultipathFunc(ctx, clusterName, target)
}

// RemoveStorageTargetMultipathCalls gets all the calls that were made to RemoveStorageTargetMultipath.
// Check the length with:
//
//	len(mockedClusterService.RemoveStorageTargetMultipathCalls())
func (mock *ClusterServiceMock) RemoveStorageTargetMultipathCalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      string
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      string
	}
	mock.lockRemoveStorageTargetMultipath.RLock()
	calls = mock.calls.RemoveStorageTargetMultipath
	mock.lockRemoveStorageTargetMultipath.RUnlock()
	return calls
}

// RemoveStorageTargetNVME calls RemoveStorageTargetNVMEFunc.
func (mock *ClusterServiceMock) RemoveStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) error {
	if mock.RemoveStorageTargetNVMEFunc == nil {
		panic("ClusterServiceMock.RemoveStorageTargetNVMEFunc: method is nil but ClusterService.RemoveStorageTargetNVME was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceNVMETarget
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		Target:      target,
	}
	mock.lockRemoveStorageTargetNVME.Lock()
	mock.calls.RemoveStorageTargetNVME = append(mock.calls.RemoveStorageTargetNVME, callInfo)
	mock.lockRemoveStorageTargetNVME.Unlock()
	return mock.RemoveStorageTargetNVMEFunc(ctx, clusterName, target)
}

// RemoveStorageTargetNVMECalls gets all the calls that were made to RemoveStorageTargetNVME.
// Check the length with:
//
//	len(mockedClusterService.RemoveStorageTargetNVMECalls())
func (mock *ClusterServiceMock) RemoveStorageTargetNVMECalls() []struct {
	Ctx         context.Context
	ClusterName string
	Target      api.ServiceNVMETarget
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		Target      api.ServiceNVMETarget
	}
	mock.lockRemoveStorageTargetNVME.RLock()
	calls = mock.calls.RemoveStorageTargetNVME
	mock.lockRemoveStorageTargetNVME.RUnlock()
	return calls
}

// Rename calls RenameFunc.
func (mock *ClusterServiceMock) Rename(ctx context.Context, oldName string, newName string) error {
	if mock.RenameFunc == nil {
		panic("ClusterServiceMock.RenameFunc: method is nil but ClusterService.Rename was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OldName string
		NewName string
	}{
		Ctx:     ctx,
		OldName: oldName,
		NewName: newName,
	}
	mock.lockRename.Lock()
	mock.calls.Rename = append(mock.calls.Rename, callInfo)
	mock.lockRename.Unlock()
	return mock.RenameFunc(ctx, oldName, newName)
}

// RenameCalls gets all the calls that were made to Rename.
// Check the length with:
//
//	len(mockedClusterService.RenameCalls())
func (mock *ClusterServiceMock) RenameCalls() []struct {
	Ctx     context.Context
	OldName string
	NewName string
} {
	var calls []struct {
		Ctx     context.Context
		OldName string
		NewName string
	}
	mock.lockRename.RLock()
	calls = mock.calls.Rename
	mock.lockRename.RUnlock()
	return calls
}

// ResyncInventory calls ResyncInventoryFunc.
func (mock *ClusterServiceMock) ResyncInventory(ctx context.Context) error {
	if mock.ResyncInventoryFunc == nil {
		panic("ClusterServiceMock.ResyncInventoryFunc: method is nil but ClusterService.ResyncInventory was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockResyncInventory.Lock()
	mock.calls.ResyncInventory = append(mock.calls.ResyncInventory, callInfo)
	mock.lockResyncInventory.Unlock()
	return mock.ResyncInventoryFunc(ctx)
}

// ResyncInventoryCalls gets all the calls that were made to ResyncInventory.
// Check the length with:
//
//	len(mockedClusterService.ResyncInventoryCalls())
func (mock *ClusterServiceMock) ResyncInventoryCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockResyncInventory.RLock()
	calls = mock.calls.ResyncInventory
	mock.lockResyncInventory.RUnlock()
	return calls
}

// ResyncInventoryByName calls ResyncInventoryByNameFunc.
func (mock *ClusterServiceMock) ResyncInventoryByName(ctx context.Context, name string) error {
	if mock.ResyncInventoryByNameFunc == nil {
		panic("ClusterServiceMock.ResyncInventoryByNameFunc: method is nil but ClusterService.ResyncInventoryByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockResyncInventoryByName.Lock()
	mock.calls.ResyncInventoryByName = append(mock.calls.ResyncInventoryByName, callInfo)
	mock.lockResyncInventoryByName.Unlock()
	return mock.ResyncInventoryByNameFunc(ctx, name)
}

// ResyncInventoryByNameCalls gets all the calls that were made to ResyncInventoryByName.
// Check the length with:
//
//	len(mockedClusterService.ResyncInventoryByNameCalls())
func (mock *ClusterServiceMock) ResyncInventoryByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockResyncInventoryByName.RLock()
	calls = mock.calls.ResyncInventoryByName
	mock.lockResyncInventoryByName.RUnlock()
	return calls
}

// SetInventorySyncers calls SetInventorySyncersFunc.
func (mock *ClusterServiceMock) SetInventorySyncers(inventorySyncers map[domain.ResourceType]provisioning.InventorySyncer) {
	if mock.SetInventorySyncersFunc == nil {
		panic("ClusterServiceMock.SetInventorySyncersFunc: method is nil but ClusterService.SetInventorySyncers was just called")
	}
	callInfo := struct {
		InventorySyncers map[domain.ResourceType]provisioning.InventorySyncer
	}{
		InventorySyncers: inventorySyncers,
	}
	mock.lockSetInventorySyncers.Lock()
	mock.calls.SetInventorySyncers = append(mock.calls.SetInventorySyncers, callInfo)
	mock.lockSetInventorySyncers.Unlock()
	mock.SetInventorySyncersFunc(inventorySyncers)
}

// SetInventorySyncersCalls gets all the calls that were made to SetInventorySyncers.
// Check the length with:
//
//	len(mockedClusterService.SetInventorySyncersCalls())
func (mock *ClusterServiceMock) SetInventorySyncersCalls() []struct {
	InventorySyncers map[domain.ResourceType]provisioning.InventorySyncer
} {
	var calls []struct {
		InventorySyncers map[domain.ResourceType]provisioning.InventorySyncer
	}
	mock.lockSetInventorySyncers.RLock()
	calls = mock.calls.SetInventorySyncers
	mock.lockSetInventorySyncers.RUnlock()
	return calls
}

// StartLifecycleEventsMonitor calls StartLifecycleEventsMonitorFunc.
func (mock *ClusterServiceMock) StartLifecycleEventsMonitor(ctx context.Context) error {
	if mock.StartLifecycleEventsMonitorFunc == nil {
		panic("ClusterServiceMock.StartLifecycleEventsMonitorFunc: method is nil but ClusterService.StartLifecycleEventsMonitor was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStartLifecycleEventsMonitor.Lock()
	mock.calls.StartLifecycleEventsMonitor = append(mock.calls.StartLifecycleEventsMonitor, callInfo)
	mock.lockStartLifecycleEventsMonitor.Unlock()
	return mock.StartLifecycleEventsMonitorFunc(ctx)
}

// StartLifecycleEventsMonitorCalls gets all the calls that were made to StartLifecycleEventsMonitor.
// Check the length with:
//
//	len(mockedClusterService.StartLifecycleEventsMonitorCalls())
func (mock *ClusterServiceMock) StartLifecycleEventsMonitorCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStartLifecycleEventsMonitor.RLock()
	calls = mock.calls.StartLifecycleEventsMonitor
	mock.lockStartLifecycleEventsMonitor.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ClusterServiceMock) Update(ctx context.Context, cluster provisioning.Cluster, updateServers bool) error {
	if mock.UpdateFunc == nil {
		panic("ClusterServiceMock.UpdateFunc: method is nil but ClusterService.Update was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Cluster       provisioning.Cluster
		UpdateServers bool
	}{
		Ctx:           ctx,
		Cluster:       cluster,
		UpdateServers: updateServers,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, cluster, updateServers)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedClusterService.UpdateCalls())
func (mock *ClusterServiceMock) UpdateCalls() []struct {
	Ctx           context.Context
	Cluster       provisioning.Cluster
	UpdateServers bool
} {
	var calls []struct {
		Ctx           context.Context
		Cluster       provisioning.Cluster
		UpdateServers bool
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateCertificate calls UpdateCertificateFunc.
func (mock *ClusterServiceMock) UpdateCertificate(ctx context.Context, name string, certificatePEM string, keyPEM string) error {
	if mock.UpdateCertificateFunc == nil {
		panic("ClusterServiceMock.UpdateCertificateFunc: method is nil but ClusterService.UpdateCertificate was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Name           string
		CertificatePEM string
		KeyPEM         string
	}{
		Ctx:            ctx,
		Name:           name,
		CertificatePEM: certificatePEM,
		KeyPEM:         keyPEM,
	}
	mock.lockUpdateCertificate.Lock()
	mock.calls.UpdateCertificate = append(mock.calls.UpdateCertificate, callInfo)
	mock.lockUpdateCertificate.Unlock()
	return mock.UpdateCertificateFunc(ctx, name, certificatePEM, keyPEM)
}

// UpdateCertificateCalls gets all the calls that were made to UpdateCertificate.
// Check the length with:
//
//	len(mockedClusterService.UpdateCertificateCalls())
func (mock *ClusterServiceMock) UpdateCertificateCalls() []struct {
	Ctx            context.Context
	Name           string
	CertificatePEM string
	KeyPEM         string
} {
	var calls []struct {
		Ctx            context.Context
		Name           string
		CertificatePEM string
		KeyPEM         string
	}
	mock.lockUpdateCertificate.RLock()
	calls = mock.calls.UpdateCertificate
	mock.lockUpdateCertificate.RUnlock()
	return calls
}

// UpdateSystemKernel calls UpdateSystemKernelFunc.
func (mock *ClusterServiceMock) UpdateSystemKernel(ctx context.Context, clusterName string, kerneConfig provisioning.ServerSystemKernel) error {
	if mock.UpdateSystemKernelFunc == nil {
		panic("ClusterServiceMock.UpdateSystemKernelFunc: method is nil but ClusterService.UpdateSystemKernel was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ClusterName string
		KerneConfig provisioning.ServerSystemKernel
	}{
		Ctx:         ctx,
		ClusterName: clusterName,
		KerneConfig: kerneConfig,
	}
	mock.lockUpdateSystemKernel.Lock()
	mock.calls.UpdateSystemKernel = append(mock.calls.UpdateSystemKernel, callInfo)
	mock.lockUpdateSystemKernel.Unlock()
	return mock.UpdateSystemKernelFunc(ctx, clusterName, kerneConfig)
}

// UpdateSystemKernelCalls gets all the calls that were made to UpdateSystemKernel.
// Check the length with:
//
//	len(mockedClusterService.UpdateSystemKernelCalls())
func (mock *ClusterServiceMock) UpdateSystemKernelCalls() []struct {
	Ctx         context.Context
	ClusterName string
	KerneConfig provisioning.ServerSystemKernel
} {
	var calls []struct {
		Ctx         context.Context
		ClusterName string
		KerneConfig provisioning.ServerSystemKernel
	}
	mock.lockUpdateSystemKernel.RLock()
	calls = mock.calls.UpdateSystemKernel
	mock.lockUpdateSystemKernel.RUnlock()
	return calls
}

// UpdateSystemLogging calls UpdateSystemLoggingFunc.
func (mock *ClusterServiceMock) UpdateSystemLogging(ctx context.Context, clusterName string, loggingConfig provisioning.ServerSystemLogging) error {
	if mock.UpdateSystemLoggingFunc == nil {
		panic("ClusterServiceMock.UpdateSystemLoggingFunc: method is nil but ClusterService.UpdateSystemLogging was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ClusterName   string
		LoggingConfig provisioning.ServerSystemLogging
	}{
		Ctx:           ctx,
		ClusterName:   clusterName,
		LoggingConfig: loggingConfig,
	}
	mock.lockUpdateSystemLogging.Lock()
	mock.calls.UpdateSystemLogging = append(mock.calls.UpdateSystemLogging, callInfo)
	mock.lockUpdateSystemLogging.Unlock()
	return mock.UpdateSystemLoggingFunc(ctx, clusterName, loggingConfig)
}

// UpdateSystemLoggingCalls gets all the calls that were made to UpdateSystemLogging.
// Check the length with:
//
//	len(mockedClusterService.UpdateSystemLoggingCalls())
func (mock *ClusterServiceMock) UpdateSystemLoggingCalls() []struct {
	Ctx           context.Context
	ClusterName   string
	LoggingConfig provisioning.ServerSystemLogging
} {
	var calls []struct {
		Ctx           context.Context
		ClusterName   string
		LoggingConfig provisioning.ServerSystemLogging
	}
	mock.lockUpdateSystemLogging.RLock()
	calls = mock.calls.UpdateSystemLogging
	mock.lockUpdateSystemLogging.RUnlock()
	return calls
}
