// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"archive/tar"
	"context"
	"io"
	"log/slog"

	"github.com/google/uuid"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/file"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// componentUpdateFilesRepo identifies the log records of this decorator and allows the
// log level to be configured for it individually.
var componentUpdateFilesRepo = logger.RegisterComponent("provisioning.update_files_repo")

// UpdateFilesRepoWithSlog implements provisioning.UpdateFilesRepo that is instrumented with slog logger.
type UpdateFilesRepoWithSlog struct {
	_base      provisioning.UpdateFilesRepo
	_component logger.Component
}

type UpdateFilesRepoWithSlogOption func(s *UpdateFilesRepoWithSlog)

// UpdateFilesRepoWithSlogWithComponent overrides the component this instance is
// attributed to. Use it to tell several instances of the same interface apart,
// e.g. the individual members of a chain.
func UpdateFilesRepoWithSlogWithComponent(component logger.Component) UpdateFilesRepoWithSlogOption {
	return func(_base *UpdateFilesRepoWithSlog) {
		_base._component = component
	}
}

// NewUpdateFilesRepoWithSlog instruments an implementation of the provisioning.UpdateFilesRepo with simple logging.
func NewUpdateFilesRepoWithSlog(base provisioning.UpdateFilesRepo, opts ...UpdateFilesRepoWithSlogOption) UpdateFilesRepoWithSlog {
	this := UpdateFilesRepoWithSlog{
		_base:      base,
		_component: componentUpdateFilesRepo,
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// CleanupAll implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) CleanupAll(ctx context.Context) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling CleanupAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method CleanupAll returned an error")
		} else {
			log.DebugContext(ctx, "<= method CleanupAll finished")
		}
	}()
	return _d._base.CleanupAll(ctx)
}

// CreateFromArchive implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) CreateFromArchive(ctx context.Context, tarReader *tar.Reader) (update *provisioning.Update, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("tarReader", tarReader),
		)
	}
	log.DebugContext(ctx, "=> calling CreateFromArchive")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("update", update),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method CreateFromArchive returned an error")
		} else {
			log.DebugContext(ctx, "<= method CreateFromArchive finished")
		}
	}()
	return _d._base.CreateFromArchive(ctx, tarReader)
}

// Delete implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) Delete(ctx context.Context, update provisioning.Update) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("update", update),
		)
	}
	log.DebugContext(ctx, "=> calling Delete")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Delete returned an error")
		} else {
			log.DebugContext(ctx, "<= method Delete finished")
		}
	}()
	return _d._base.Delete(ctx, update)
}

// DeleteUnknown implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) DeleteUnknown(ctx context.Context, known []uuid.UUID) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("known", known),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteUnknown")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method DeleteUnknown returned an error")
		} else {
			log.DebugContext(ctx, "<= method DeleteUnknown finished")
		}
	}()
	return _d._base.DeleteUnknown(ctx, known)
}

// Exists implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) Exists(ctx context.Context, update provisioning.Update, filename string) (b bool, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("update", update),
			slog.String("filename", filename),
		)
	}
	log.DebugContext(ctx, "=> calling Exists")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Bool("b", b),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Exists returned an error")
		} else {
			log.DebugContext(ctx, "<= method Exists finished")
		}
	}()
	return _d._base.Exists(ctx, update, filename)
}

// Get implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) Get(ctx context.Context, update provisioning.Update, filename string) (readCloser io.ReadCloser, size int, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("update", update),
			slog.String("filename", filename),
		)
	}
	log.DebugContext(ctx, "=> calling Get")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("readCloser", readCloser),
				slog.Int("size", size),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Get returned an error")
		} else {
			log.DebugContext(ctx, "<= method Get finished")
		}
	}()
	return _d._base.Get(ctx, update, filename)
}

// PruneFiles implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) PruneFiles(ctx context.Context, update provisioning.Update) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("update", update),
		)
	}
	log.DebugContext(ctx, "=> calling PruneFiles")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method PruneFiles returned an error")
		} else {
			log.DebugContext(ctx, "<= method PruneFiles finished")
		}
	}()
	return _d._base.PruneFiles(ctx, update)
}

// Put implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) Put(ctx context.Context, update provisioning.Update, filename string, content io.ReadCloser) (commitFunc provisioning.CommitFunc, cancelFunc provisioning.CancelFunc, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("update", update),
			slog.String("filename", filename),
			slog.Any("content", content),
		)
	}
	log.DebugContext(ctx, "=> calling Put")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("commitFunc", commitFunc),
				slog.Any("cancelFunc", cancelFunc),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Put returned an error")
		} else {
			log.DebugContext(ctx, "<= method Put finished")
		}
	}()
	return _d._base.Put(ctx, update, filename, content)
}

// UsageInformation implements provisioning.UpdateFilesRepo.
func (_d UpdateFilesRepoWithSlog) UsageInformation(ctx context.Context) (usageInformation file.UsageInformation, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling UsageInformation")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("usageInformation", usageInformation),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method UsageInformation returned an error")
		} else {
			log.DebugContext(ctx, "<= method UsageInformation finished")
		}
	}()
	return _d._base.UsageInformation(ctx)
}
