// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/system"
)

// Ensure that DatabaseRepoMock does implement system.DatabaseRepo.
// If this is not the case, regenerate this file with mockery.
var _ system.DatabaseRepo = &DatabaseRepoMock{}

// DatabaseRepoMock is a mock implementation of system.DatabaseRepo.
//
//	func TestSomethingThatUsesDatabaseRepo(t *testing.T) {
//
//		// make and configure a mocked system.DatabaseRepo
//		mockedDatabaseRepo := &DatabaseRepoMock{
//			SchemaVersionFunc: func(ctx context.Context, dir string) (int, int, error) {
//				panic("mock out the SchemaVersion method")
//			},
//			SnapshotFunc: func(ctx context.Context, dir string) error {
//				panic("mock out the Snapshot method")
//			},
//		}
//
//		// use mockedDatabaseRepo in code that requires system.DatabaseRepo
//		// and then make assertions.
//
//	}
type DatabaseRepoMock struct {
	// SchemaVersionFunc mocks the SchemaVersion method.
	SchemaVersionFunc func(ctx context.Context, dir string) (int, int, error)

	// SnapshotFunc mocks the Snapshot method.
	SnapshotFunc func(ctx context.Context, dir string) error

	// calls tracks calls to the methods.
	calls struct {
		// SchemaVersion holds details about calls to the SchemaVersion method.
		SchemaVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dir is the dir argument value.
			Dir string
		}
		// Snapshot holds details about calls to the Snapshot method.
		Snapshot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockSchemaVersion sync.RWMutex
	lockSnapshot      sync.RWMutex
}

// SchemaVersion calls SchemaVersionFunc.
func (mock *DatabaseRepoMock) SchemaVersion(ctx context.Context, dir string) (int, int, error) {
	if mock.SchemaVersionFunc == nil {
		panic("DatabaseRepoMock.SchemaVersionFunc: method is nil but DatabaseRepo.SchemaVersion was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dir string
	}{
		Ctx: ctx,
		Dir: dir,
	}
	mock.lockSchemaVersion.Lock()
	mock.calls.SchemaVersion = append(mock.calls.SchemaVersion, callInfo)
	mock.lockSchemaVersion.Unlock()
	return mock.SchemaVersionFunc(ctx, dir)
}

// SchemaVersionCalls gets all the calls that were made to SchemaVersion.
// Check the length with:
//
//	len(mockedDatabaseRepo.SchemaVersionCalls())
func (mock *DatabaseRepoMock) SchemaVersionCalls() []struct {
	Ctx context.Context
	Dir string
} {
	var calls []struct {
		Ctx context.Context
		Dir string
	}
	mock.lockSchemaVersion.RLock()
	calls = mock.calls.SchemaVersion
	mock.lockSchemaVersion.RUnlock()
	return calls
}

// Snapshot calls SnapshotFunc.
func (mock *DatabaseRepoMock) Snapshot(ctx context.Context, dir string) error {
	if mock.SnapshotFunc == nil {
		panic("DatabaseRepoMock.SnapshotFunc: method is nil but DatabaseRepo.Snapshot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dir string
	}{
		Ctx: ctx,
		Dir: dir,
	}
	mock.lockSnapshot.Lock()
	mock.calls.Snapshot = append(mock.calls.Snapshot, callInfo)
	mock.lockSnapshot.Unlock()
	return mock.SnapshotFunc(ctx, dir)
}

// SnapshotCalls gets all the calls that were made to Snapshot.
// Check the length with:
//
//	len(mockedDatabaseRepo.SnapshotCalls())
func (mock *DatabaseRepoMock) SnapshotCalls() []struct {
	Ctx context.Context
	Dir string
} {
	var calls []struct {
		Ctx context.Context
		Dir string
	}
	mock.lockSnapshot.RLock()
	calls = mock.calls.Snapshot
	mock.lockSnapshot.RUnlock()
	return calls
}
