// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"io"
	"time"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/google/uuid"
	"github.com/lxc/incus-os/incus-osd/api"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// ClusterServiceWithPrometheus implements provisioning.ClusterService interface with all methods wrapped
// with Prometheus metrics.
type ClusterServiceWithPrometheus struct {
	base         provisioning.ClusterService
	instanceName string
}

var clusterServiceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "cluster_service_duration_seconds",
		Help:       "clusterService runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewClusterServiceWithPrometheus returns an instance of the provisioning.ClusterService decorated with prometheus summary metric.
func NewClusterServiceWithPrometheus(base provisioning.ClusterService, instanceName string) ClusterServiceWithPrometheus {
	return ClusterServiceWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// AbortClusterUpdate implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AbortClusterUpdate(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AbortClusterUpdate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AbortClusterUpdate(ctx, name)
}

// AddApplication implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddApplication(ctx context.Context, clusterName string, applicationName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddApplication", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddApplication(ctx, clusterName, applicationName)
}

// AddServerSystemNetworkVLANTags implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddServerSystemNetworkVLANTags", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddServerSystemNetworkVLANTags(ctx, clusterName, interfaceName, vlanTags)
}

// AddServers implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddServers(ctx context.Context, name string, serverNames []string, skipPostJoinOperations bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddServers", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddServers(ctx, name, serverNames, skipPostJoinOperations)
}

// AddStorageTargetISCSI implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddStorageTargetISCSI", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddStorageTargetISCSI(ctx, clusterName, target)
}

// AddStorageTargetMultipath implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddStorageTargetMultipath(ctx context.Context, clusterName string, target string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddStorageTargetMultipath", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddStorageTargetMultipath(ctx, clusterName, target)
}

// AddStorageTargetNVME implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) AddStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "AddStorageTargetNVME", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.AddStorageTargetNVME(ctx, clusterName, target)
}

// ClusterUpdateControlLoop implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) ClusterUpdateControlLoop(ctx context.Context, clusterNameFilter *string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ClusterUpdateControlLoop", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ClusterUpdateControlLoop(ctx, clusterNameFilter)
}

// Create implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) Create(ctx context.Context, cluster provisioning.Cluster) (cluster1 provisioning.Cluster, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Create", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Create(ctx, cluster)
}

// DeleteAndFactoryResetByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) DeleteAndFactoryResetByName(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteAndFactoryResetByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteAndFactoryResetByName(ctx, name, tokenID, tokenSeedName)
}

// DeleteByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) DeleteByName(ctx context.Context, name string, force bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteByName(ctx, name, force)
}

// GetAll implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetAll(ctx context.Context) (clusters provisioning.Clusters, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAll", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAll(ctx)
}

// GetAllNames implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetAllNames(ctx context.Context) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNames", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNames(ctx)
}

// GetAllNamesWithFilter implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ClusterFilter) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllNamesWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllNamesWithFilter(ctx, filter)
}

// GetAllWithFilter implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetAllWithFilter(ctx context.Context, filter provisioning.ClusterFilter) (clusters provisioning.Clusters, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllWithFilter(ctx, filter)
}

// GetByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetByName(ctx context.Context, name string) (cluster *provisioning.Cluster, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByName(ctx, name)
}

// GetClusterArtifactAll implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetClusterArtifactAll(ctx context.Context, clusterName string) (clusterArtifacts provisioning.ClusterArtifacts, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactAll", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactAll(ctx, clusterName)
}

// GetClusterArtifactAllNames implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetClusterArtifactAllNames(ctx context.Context, clusterName string) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactAllNames", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactAllNames(ctx, clusterName)
}

// GetClusterArtifactArchiveByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetClusterArtifactArchiveByName(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (readCloser io.ReadCloser, size int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactArchiveByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactArchiveByName(ctx, clusterName, artifactName, archiveType)
}

// GetClusterArtifactByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetClusterArtifactByName(ctx context.Context, clusterName string, artifactName string) (clusterArtifact *provisioning.ClusterArtifact, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactByName(ctx, clusterName, artifactName)
}

// GetClusterArtifactFileByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetClusterArtifactFileByName(ctx context.Context, clusterName string, artifactName string, filename string) (clusterArtifactFile *provisioning.ClusterArtifactFile, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactFileByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactFileByName(ctx, clusterName, artifactName, filename)
}

// GetEndpoint implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) GetEndpoint(ctx context.Context, name string) (endpoint provisioning.Endpoint, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetEndpoint", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetEndpoint(ctx, name)
}

// IsInstanceLifecycleOperationPermitted implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) IsInstanceLifecycleOperationPermitted(ctx context.Context, name string) (b bool) {
	_since := time.Now()
	defer func() {
		result := "ok"
		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "IsInstanceLifecycleOperationPermitted", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.IsInstanceLifecycleOperationPermitted(ctx, name)
}

// LaunchClusterUpdate implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) LaunchClusterUpdate(ctx context.Context, name string, reboot bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "LaunchClusterUpdate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.LaunchClusterUpdate(ctx, name, reboot)
}

// RemoveServer implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) RemoveServer(ctx context.Context, name string, removedServerNames []string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RemoveServer", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RemoveServer(ctx, name, removedServerNames)
}

// RemoveServerSystemNetworkVLANTags implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) RemoveServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RemoveServerSystemNetworkVLANTags", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RemoveServerSystemNetworkVLANTags(ctx, clusterName, interfaceName, vlanTags)
}

// RemoveStorageTargetISCSI implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) RemoveStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RemoveStorageTargetISCSI", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RemoveStorageTargetISCSI(ctx, clusterName, target)
}

// RemoveStorageTargetMultipath implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) RemoveStorageTargetMultipath(ctx context.Context, clusterName string, target string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RemoveStorageTargetMultipath", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RemoveStorageTargetMultipath(ctx, clusterName, target)
}

// RemoveStorageTargetNVME implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) RemoveStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "RemoveStorageTargetNVME", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.RemoveStorageTargetNVME(ctx, clusterName, target)
}

// Rename implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) Rename(ctx context.Context, oldName string, newName string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Rename", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Rename(ctx, oldName, newName)
}

// ResyncInventory implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) ResyncInventory(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncInventory", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncInventory(ctx)
}

// ResyncInventoryByName implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) ResyncInventoryByName(ctx context.Context, name string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncInventoryByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncInventoryByName(ctx, name)
}

// SetInventorySyncers implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) SetInventorySyncers(inventorySyncers map[domain.ResourceType]provisioning.InventorySyncer) {
	_since := time.Now()
	defer func() {
		result := "ok"
		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SetInventorySyncers", result).Observe(time.Since(_since).Seconds())
	}()
	_d.base.SetInventorySyncers(inventorySyncers)
}

// StartLifecycleEventsMonitor implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) StartLifecycleEventsMonitor(ctx context.Context) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "StartLifecycleEventsMonitor", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.StartLifecycleEventsMonitor(ctx)
}

// Update implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) Update(ctx context.Context, cluster provisioning.Cluster, updateServers bool) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "Update", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Update(ctx, cluster, updateServers)
}

// UpdateCertificate implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) UpdateCertificate(ctx context.Context, name string, certificatePEM string, keyPEM string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateCertificate", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateCertificate(ctx, name, certificatePEM, keyPEM)
}

// UpdateSystemKernel implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) UpdateSystemKernel(ctx context.Context, clusterName string, kerneConfig provisioning.ServerSystemKernel) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemKernel", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemKernel(ctx, clusterName, kerneConfig)
}

// UpdateSystemLogging implements provisioning.ClusterService.
func (_d ClusterServiceWithPrometheus) UpdateSystemLogging(ctx context.Context, clusterName string, loggingConfig provisioning.ServerSystemLogging) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateSystemLogging", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateSystemLogging(ctx, clusterName, loggingConfig)
}
