// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"io"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/google/uuid"
	"github.com/lxc/incus-os/incus-osd/api"
)

// ClusterServiceWithSlog implements provisioning.ClusterService that is instrumented with slog logger.
type ClusterServiceWithSlog struct {
	_base                 provisioning.ClusterService
	_isInformativeErrFunc func(error) bool
}

type ClusterServiceWithSlogOption func(s *ClusterServiceWithSlog)

func ClusterServiceWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) ClusterServiceWithSlogOption {
	return func(_base *ClusterServiceWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewClusterServiceWithSlog instruments an implementation of the provisioning.ClusterService with simple logging.
func NewClusterServiceWithSlog(base provisioning.ClusterService, opts ...ClusterServiceWithSlogOption) ClusterServiceWithSlog {
	this := ClusterServiceWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// AbortClusterUpdate implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AbortClusterUpdate(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling AbortClusterUpdate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AbortClusterUpdate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AbortClusterUpdate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AbortClusterUpdate finished")
		}
	}()
	return _d._base.AbortClusterUpdate(ctx, name)
}

// AddApplication implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddApplication(ctx context.Context, clusterName string, applicationName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("applicationName", applicationName),
		)
	}
	log.DebugContext(ctx, "=> calling AddApplication")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddApplication returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddApplication returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddApplication finished")
		}
	}()
	return _d._base.AddApplication(ctx, clusterName, applicationName)
}

// AddServerSystemNetworkVLANTags implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("interfaceName", interfaceName),
			slog.Any("vlanTags", vlanTags),
		)
	}
	log.DebugContext(ctx, "=> calling AddServerSystemNetworkVLANTags")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddServerSystemNetworkVLANTags returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddServerSystemNetworkVLANTags returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddServerSystemNetworkVLANTags finished")
		}
	}()
	return _d._base.AddServerSystemNetworkVLANTags(ctx, clusterName, interfaceName, vlanTags)
}

// AddServers implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddServers(ctx context.Context, name string, serverNames []string, skipPostJoinOperations bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("serverNames", serverNames),
			slog.Bool("skipPostJoinOperations", skipPostJoinOperations),
		)
	}
	log.DebugContext(ctx, "=> calling AddServers")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddServers returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddServers returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddServers finished")
		}
	}()
	return _d._base.AddServers(ctx, name, serverNames, skipPostJoinOperations)
}

// AddStorageTargetISCSI implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling AddStorageTargetISCSI")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddStorageTargetISCSI returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddStorageTargetISCSI returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddStorageTargetISCSI finished")
		}
	}()
	return _d._base.AddStorageTargetISCSI(ctx, clusterName, target)
}

// AddStorageTargetMultipath implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddStorageTargetMultipath(ctx context.Context, clusterName string, target string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling AddStorageTargetMultipath")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddStorageTargetMultipath returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddStorageTargetMultipath returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddStorageTargetMultipath finished")
		}
	}()
	return _d._base.AddStorageTargetMultipath(ctx, clusterName, target)
}

// AddStorageTargetNVME implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) AddStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling AddStorageTargetNVME")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method AddStorageTargetNVME returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method AddStorageTargetNVME returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method AddStorageTargetNVME finished")
		}
	}()
	return _d._base.AddStorageTargetNVME(ctx, clusterName, target)
}

// ClusterUpdateControlLoop implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) ClusterUpdateControlLoop(ctx context.Context, clusterNameFilter *string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("clusterNameFilter", clusterNameFilter),
		)
	}
	log.DebugContext(ctx, "=> calling ClusterUpdateControlLoop")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ClusterUpdateControlLoop returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ClusterUpdateControlLoop returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ClusterUpdateControlLoop finished")
		}
	}()
	return _d._base.ClusterUpdateControlLoop(ctx, clusterNameFilter)
}

// Create implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) Create(ctx context.Context, cluster provisioning.Cluster) (cluster1 provisioning.Cluster, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cluster", cluster),
		)
	}
	log.DebugContext(ctx, "=> calling Create")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("cluster1", cluster1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Create returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Create returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Create finished")
		}
	}()
	return _d._base.Create(ctx, cluster)
}

// DeleteAndFactoryResetByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) DeleteAndFactoryResetByName(ctx context.Context, name string, tokenID *uuid.UUID, tokenSeedName *string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("tokenID", tokenID),
			slog.Any("tokenSeedName", tokenSeedName),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteAndFactoryResetByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeleteAndFactoryResetByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeleteAndFactoryResetByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeleteAndFactoryResetByName finished")
		}
	}()
	return _d._base.DeleteAndFactoryResetByName(ctx, name, tokenID, tokenSeedName)
}

// DeleteByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) DeleteByName(ctx context.Context, name string, force bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("force", force),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeleteByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeleteByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name, force)
}

// GetAll implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetAll(ctx context.Context) (clusters provisioning.Clusters, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusters", clusters),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAll returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAll returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetAllNames implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetAllNames(ctx context.Context) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllNames")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllNames returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllNames returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllNames finished")
		}
	}()
	return _d._base.GetAllNames(ctx)
}

// GetAllNamesWithFilter implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetAllNamesWithFilter(ctx context.Context, filter provisioning.ClusterFilter) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllNamesWithFilter")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllNamesWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllNamesWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllNamesWithFilter finished")
		}
	}()
	return _d._base.GetAllNamesWithFilter(ctx, filter)
}

// GetAllWithFilter implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetAllWithFilter(ctx context.Context, filter provisioning.ClusterFilter) (clusters provisioning.Clusters, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllWithFilter")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusters", clusters),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllWithFilter finished")
		}
	}()
	return _d._base.GetAllWithFilter(ctx, filter)
}

// GetByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetByName(ctx context.Context, name string) (cluster *provisioning.Cluster, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("cluster", cluster),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// GetClusterArtifactAll implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetClusterArtifactAll(ctx context.Context, clusterName string) (clusterArtifacts provisioning.ClusterArtifacts, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
		)
	}
	log.DebugContext(ctx, "=> calling GetClusterArtifactAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterArtifacts", clusterArtifacts),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetClusterArtifactAll returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetClusterArtifactAll returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetClusterArtifactAll finished")
		}
	}()
	return _d._base.GetClusterArtifactAll(ctx, clusterName)
}

// GetClusterArtifactAllNames implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetClusterArtifactAllNames(ctx context.Context, clusterName string) (strings []string, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
		)
	}
	log.DebugContext(ctx, "=> calling GetClusterArtifactAllNames")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetClusterArtifactAllNames returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetClusterArtifactAllNames returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetClusterArtifactAllNames finished")
		}
	}()
	return _d._base.GetClusterArtifactAllNames(ctx, clusterName)
}

// GetClusterArtifactArchiveByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetClusterArtifactArchiveByName(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (readCloser io.ReadCloser, size int, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("artifactName", artifactName),
			slog.Any("archiveType", archiveType),
		)
	}
	log.DebugContext(ctx, "=> calling GetClusterArtifactArchiveByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("readCloser", readCloser),
				slog.Int("size", size),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetClusterArtifactArchiveByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetClusterArtifactArchiveByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetClusterArtifactArchiveByName finished")
		}
	}()
	return _d._base.GetClusterArtifactArchiveByName(ctx, clusterName, artifactName, archiveType)
}

// GetClusterArtifactByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetClusterArtifactByName(ctx context.Context, clusterName string, artifactName string) (clusterArtifact *provisioning.ClusterArtifact, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("artifactName", artifactName),
		)
	}
	log.DebugContext(ctx, "=> calling GetClusterArtifactByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterArtifact", clusterArtifact),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetClusterArtifactByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetClusterArtifactByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetClusterArtifactByName finished")
		}
	}()
	return _d._base.GetClusterArtifactByName(ctx, clusterName, artifactName)
}

// GetClusterArtifactFileByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetClusterArtifactFileByName(ctx context.Context, clusterName string, artifactName string, filename string) (clusterArtifactFile *provisioning.ClusterArtifactFile, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("artifactName", artifactName),
			slog.String("filename", filename),
		)
	}
	log.DebugContext(ctx, "=> calling GetClusterArtifactFileByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterArtifactFile", clusterArtifactFile),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetClusterArtifactFileByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetClusterArtifactFileByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetClusterArtifactFileByName finished")
		}
	}()
	return _d._base.GetClusterArtifactFileByName(ctx, clusterName, artifactName, filename)
}

// GetEndpoint implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) GetEndpoint(ctx context.Context, name string) (endpoint provisioning.Endpoint, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetEndpoint")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("endpoint", endpoint),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetEndpoint returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetEndpoint returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetEndpoint finished")
		}
	}()
	return _d._base.GetEndpoint(ctx, name)
}

// IsInstanceLifecycleOperationPermitted implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) IsInstanceLifecycleOperationPermitted(ctx context.Context, name string) (b bool) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling IsInstanceLifecycleOperationPermitted")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Bool("b", b),
			)
		} else {
		}
		log.DebugContext(ctx, "<= method IsInstanceLifecycleOperationPermitted finished")
	}()
	return _d._base.IsInstanceLifecycleOperationPermitted(ctx, name)
}

// LaunchClusterUpdate implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) LaunchClusterUpdate(ctx context.Context, name string, reboot bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Bool("reboot", reboot),
		)
	}
	log.DebugContext(ctx, "=> calling LaunchClusterUpdate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method LaunchClusterUpdate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method LaunchClusterUpdate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method LaunchClusterUpdate finished")
		}
	}()
	return _d._base.LaunchClusterUpdate(ctx, name, reboot)
}

// RemoveServer implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) RemoveServer(ctx context.Context, name string, removedServerNames []string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("removedServerNames", removedServerNames),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveServer")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RemoveServer returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RemoveServer returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RemoveServer finished")
		}
	}()
	return _d._base.RemoveServer(ctx, name, removedServerNames)
}

// RemoveServerSystemNetworkVLANTags implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) RemoveServerSystemNetworkVLANTags(ctx context.Context, clusterName string, interfaceName string, vlanTags []int) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("interfaceName", interfaceName),
			slog.Any("vlanTags", vlanTags),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveServerSystemNetworkVLANTags")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RemoveServerSystemNetworkVLANTags returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RemoveServerSystemNetworkVLANTags returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RemoveServerSystemNetworkVLANTags finished")
		}
	}()
	return _d._base.RemoveServerSystemNetworkVLANTags(ctx, clusterName, interfaceName, vlanTags)
}

// RemoveStorageTargetISCSI implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) RemoveStorageTargetISCSI(ctx context.Context, clusterName string, target api.ServiceISCSITarget) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveStorageTargetISCSI")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RemoveStorageTargetISCSI returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RemoveStorageTargetISCSI returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RemoveStorageTargetISCSI finished")
		}
	}()
	return _d._base.RemoveStorageTargetISCSI(ctx, clusterName, target)
}

// RemoveStorageTargetMultipath implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) RemoveStorageTargetMultipath(ctx context.Context, clusterName string, target string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.String("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveStorageTargetMultipath")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RemoveStorageTargetMultipath returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RemoveStorageTargetMultipath returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RemoveStorageTargetMultipath finished")
		}
	}()
	return _d._base.RemoveStorageTargetMultipath(ctx, clusterName, target)
}

// RemoveStorageTargetNVME implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) RemoveStorageTargetNVME(ctx context.Context, clusterName string, target api.ServiceNVMETarget) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("target", target),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveStorageTargetNVME")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method RemoveStorageTargetNVME returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method RemoveStorageTargetNVME returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method RemoveStorageTargetNVME finished")
		}
	}()
	return _d._base.RemoveStorageTargetNVME(ctx, clusterName, target)
}

// Rename implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) Rename(ctx context.Context, oldName string, newName string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("oldName", oldName),
			slog.String("newName", newName),
		)
	}
	log.DebugContext(ctx, "=> calling Rename")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Rename returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Rename returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Rename finished")
		}
	}()
	return _d._base.Rename(ctx, oldName, newName)
}

// ResyncInventory implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) ResyncInventory(ctx context.Context) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling ResyncInventory")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResyncInventory returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResyncInventory returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResyncInventory finished")
		}
	}()
	return _d._base.ResyncInventory(ctx)
}

// ResyncInventoryByName implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) ResyncInventoryByName(ctx context.Context, name string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling ResyncInventoryByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResyncInventoryByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResyncInventoryByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResyncInventoryByName finished")
		}
	}()
	return _d._base.ResyncInventoryByName(ctx, name)
}

// SetInventorySyncers implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) SetInventorySyncers(inventorySyncers map[domain.ResourceType]provisioning.InventorySyncer) {
	ctx := context.Background()
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("inventorySyncers", inventorySyncers),
		)
	}
	log.DebugContext(ctx, "=> calling SetInventorySyncers")
	defer func() {
		log := slog.With()
		log.DebugContext(ctx, "<= method SetInventorySyncers finished")
	}()
	_d._base.SetInventorySyncers(inventorySyncers)
}

// StartLifecycleEventsMonitor implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) StartLifecycleEventsMonitor(ctx context.Context) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling StartLifecycleEventsMonitor")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method StartLifecycleEventsMonitor returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method StartLifecycleEventsMonitor returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method StartLifecycleEventsMonitor finished")
		}
	}()
	return _d._base.StartLifecycleEventsMonitor(ctx)
}

// Update implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) Update(ctx context.Context, cluster provisioning.Cluster, updateServers bool) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("cluster", cluster),
			slog.Bool("updateServers", updateServers),
		)
	}
	log.DebugContext(ctx, "=> calling Update")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method Update returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method Update returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method Update finished")
		}
	}()
	return _d._base.Update(ctx, cluster, updateServers)
}

// UpdateCertificate implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) UpdateCertificate(ctx context.Context, name string, certificatePEM string, keyPEM string) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.String("certificatePEM", certificatePEM),
			slog.String("keyPEM", keyPEM),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateCertificate")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateCertificate returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateCertificate returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateCertificate finished")
		}
	}()
	return _d._base.UpdateCertificate(ctx, name, certificatePEM, keyPEM)
}

// UpdateSystemKernel implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) UpdateSystemKernel(ctx context.Context, clusterName string, kerneConfig provisioning.ServerSystemKernel) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("kerneConfig", kerneConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemKernel")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemKernel returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemKernel returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemKernel finished")
		}
	}()
	return _d._base.UpdateSystemKernel(ctx, clusterName, kerneConfig)
}

// UpdateSystemLogging implements provisioning.ClusterService.
func (_d ClusterServiceWithSlog) UpdateSystemLogging(ctx context.Context, clusterName string, loggingConfig provisioning.ServerSystemLogging) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("clusterName", clusterName),
			slog.Any("loggingConfig", loggingConfig),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateSystemLogging")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateSystemLogging returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateSystemLogging returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateSystemLogging finished")
		}
	}()
	return _d._base.UpdateSystemLogging(ctx, clusterName, loggingConfig)
}
