---

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Client - Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Client - Download go dependencies
        run: |
          go mod download

      - name: Client - Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: UI - Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: UI - Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ui

      - name: UI - Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
          dir: ui

      - name: Prepare uploads
        run: |
          mkdir upload
          cd upload

          tar -zcf ui.tar.gz -C ../ui/dist/ .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: upload/*
          overwrite: true
          file_glob: true
          release_name: ${{ github.ref_name }}
